import nock from "nock";
import zlib from "zlib";

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post("/v1/account/sessions/anonymous", {})
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          $id: "63247930db44d2592e57",
          $createdAt: "2022-09-16T13:25:04.903+00:00",
          userId: "63247930d9d246bab42c",
          expire: "2023-09-16T13:25:04.898+00:00",
          provider: "anonymous",
          providerUid: "",
          providerAccessToken: "",
          providerAccessTokenExpiry: "",
          providerRefreshToken: "",
          ip: "159.146.41.20",
          osCode: "",
          osName: "",
          osVersion: "",
          clientType: "library",
          clientCode: "",
          clientName: "Node Fetch",
          clientVersion: "1.0",
          clientEngine: "",
          clientEngineVersion: "",
          deviceName: "",
          deviceBrand: "",
          deviceModel: "",
          countryCode: "tr",
          countryName: "Turkey",
          current: true,
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "301",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:25:04 GMT",
      "Server",
      "Appwrite",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5_legacy=eyJpZCI6IjYzMjQ3OTMwZDlkMjQ2YmFiNDJjIiwic2VjcmV0IjoiMGI5ZjIyOGFkNGM2Mjk5MjU4Y2YwZWJiOGNjYTUyYjgwOTA4NTc0ZWMwMzczM2YzYzBlYWZkYTYyZjY4YmU3ZGRiZGY1Zjc4ZjEyZmQ3MzA1YzkwNjk4Yjc4NzM1MjVjYWQ3MTUzZjQ2ZDAyMTFjM2FjZTE1OGVjOTc0MGJjN2QyNjYxNjE3MjVmMzUxNTljM2FkZDdlYzEwYmRhOWU2ZDBmMjA4MmYwMjU1NTMzYzhlMmZkMGE3MWFiM2Y0OGU3ZjYyYWY4MmZkNmEyYjk2MjA0YTcwMTI3NzAzMDFkODgxMzcyYzZjOGY3MTFiNzZiYjgxZDNkOGYyM2FkZTcyMSJ9; expires=Sat, 16-Sep-2023 13:25:04 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5=eyJpZCI6IjYzMjQ3OTMwZDlkMjQ2YmFiNDJjIiwic2VjcmV0IjoiMGI5ZjIyOGFkNGM2Mjk5MjU4Y2YwZWJiOGNjYTUyYjgwOTA4NTc0ZWMwMzczM2YzYzBlYWZkYTYyZjY4YmU3ZGRiZGY1Zjc4ZjEyZmQ3MzA1YzkwNjk4Yjc4NzM1MjVjYWQ3MTUzZjQ2ZDAyMTFjM2FjZTE1OGVjOTc0MGJjN2QyNjYxNjE3MjVmMzUxNTljM2FkZDdlYzEwYmRhOWU2ZDBmMjA4MmYwMjU1NTMzYzhlMmZkMGE3MWFiM2Y0OGU3ZjYyYWY4MmZkNmEyYjk2MjA0YTcwMTI3NzAzMDFkODgxMzcyYzZjOGY3MTFiNzZiYjgxZDNkOGYyM2FkZTcyMSJ9; expires=Sat, 16-Sep-2023 13:25:04 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly; samesite=None",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.019235134124756",
      "X-Fallback-Cookies",
      '{"a_session_6324555073b9706cb1f5":"eyJpZCI6IjYzMjQ3OTMwZDlkMjQ2YmFiNDJjIiwic2VjcmV0IjoiMGI5ZjIyOGFkNGM2Mjk5MjU4Y2YwZWJiOGNjYTUyYjgwOTA4NTc0ZWMwMzczM2YzYzBlYWZkYTYyZjY4YmU3ZGRiZGY1Zjc4ZjEyZmQ3MzA1YzkwNjk4Yjc4NzM1MjVjYWQ3MTUzZjQ2ZDAyMTFjM2FjZTE1OGVjOTc0MGJjN2QyNjYxNjE3MjVmMzUxNTljM2FkZDdlYzEwYmRhOWU2ZDBmMjA4MmYwMjU1NTMzYzhlMmZkMGE3MWFiM2Y0OGU3ZjYyYWY4MmZkNmEyYjk2MjA0YTcwMTI3NzAzMDFkODgxMzcyYzZjOGY3MTFiNzZiYjgxZDNkOGYyM2FkZTcyMSJ9"}',
      "X-Ratelimit-Limit",
      "50",
      "X-Ratelimit-Remaining",
      "38",
      "X-Ratelimit-Reset",
      "1663336800",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .delete(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents/63245af4d15590ca1984",
    {},
  )
  .reply(204, "", [
    "Access-Control-Allow-Credentials",
    "true",
    "Access-Control-Allow-Headers",
    "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
    "Access-Control-Allow-Methods",
    "GET, POST, PUT, PATCH, DELETE",
    "Access-Control-Allow-Origin",
    "https://localhost",
    "Access-Control-Expose-Headers",
    "X-Fallback-Cookies",
    "Content-Type",
    "text/html",
    "Date",
    "Fri, 16 Sep 2022 13:25:05 GMT",
    "Server",
    "Appwrite",
    "X-Content-Type-Options",
    "nosniff",
    "X-Debug-Fallback",
    "true",
    "X-Debug-Speed",
    "0.01102089881897",
    "X-Ratelimit-Limit",
    "60",
    "X-Ratelimit-Remaining",
    "59",
    "X-Ratelimit-Reset",
    "1663334760",
    "Connection",
    "close",
  ]);
