import nock from "nock";
import zlib from "zlib";

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post("/v1/account/sessions/anonymous", {})
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          $id: "63247b642cd653ca6131",
          $createdAt: "2022-09-16T13:34:28.188+00:00",
          userId: "63247b642c0248d2a142",
          expire: "2023-09-16T13:34:28.183+00:00",
          provider: "anonymous",
          providerUid: "",
          providerAccessToken: "",
          providerAccessTokenExpiry: "",
          providerRefreshToken: "",
          ip: "159.146.41.20",
          osCode: "",
          osName: "",
          osVersion: "",
          clientType: "library",
          clientCode: "",
          clientName: "Node Fetch",
          clientVersion: "1.0",
          clientEngine: "",
          clientEngineVersion: "",
          deviceName: "",
          deviceBrand: "",
          deviceModel: "",
          countryCode: "tr",
          countryName: "Turkey",
          current: true,
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "298",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:34:28 GMT",
      "Server",
      "Appwrite",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5_legacy=eyJpZCI6IjYzMjQ3YjY0MmMwMjQ4ZDJhMTQyIiwic2VjcmV0IjoiNzM5YmQ1MmNmZjM2ZTFjOTY2ODc1MGMzYzRmN2U1ZjA1YmFiNDYwOGQ2MWZlMjdhNDkzMTc5OTBkYzVjMTIwYTlhMjA2OWUwODVjM2FhNTg5NGViM2FmYTAzMzgzOTcyMTQ1MGI1ZDg1Nzk5NzBkNWQyMTkyODBkYzBmY2UwYzk3Y2VkOGU5YTkzZWI4YTgwMjZjYzlmMmE1NjFiZDNiYjcwNzE1NzZkNjAyNjZlOTgzNGNmZDE4MzFiZmE1ZjI4MDcyYjA0ZDIzNWU4MGE1Zjk5YTg1MjJlMDVjY2VmZjJjZTVlNTljMDBiMjg2MjBkMmM4YTZjNzliYmEyY2I4ZCJ9; expires=Sat, 16-Sep-2023 13:34:28 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5=eyJpZCI6IjYzMjQ3YjY0MmMwMjQ4ZDJhMTQyIiwic2VjcmV0IjoiNzM5YmQ1MmNmZjM2ZTFjOTY2ODc1MGMzYzRmN2U1ZjA1YmFiNDYwOGQ2MWZlMjdhNDkzMTc5OTBkYzVjMTIwYTlhMjA2OWUwODVjM2FhNTg5NGViM2FmYTAzMzgzOTcyMTQ1MGI1ZDg1Nzk5NzBkNWQyMTkyODBkYzBmY2UwYzk3Y2VkOGU5YTkzZWI4YTgwMjZjYzlmMmE1NjFiZDNiYjcwNzE1NzZkNjAyNjZlOTgzNGNmZDE4MzFiZmE1ZjI4MDcyYjA0ZDIzNWU4MGE1Zjk5YTg1MjJlMDVjY2VmZjJjZTVlNTljMDBiMjg2MjBkMmM4YTZjNzliYmEyY2I4ZCJ9; expires=Sat, 16-Sep-2023 13:34:28 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly; samesite=None",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.06734299659729",
      "X-Fallback-Cookies",
      '{"a_session_6324555073b9706cb1f5":"eyJpZCI6IjYzMjQ3YjY0MmMwMjQ4ZDJhMTQyIiwic2VjcmV0IjoiNzM5YmQ1MmNmZjM2ZTFjOTY2ODc1MGMzYzRmN2U1ZjA1YmFiNDYwOGQ2MWZlMjdhNDkzMTc5OTBkYzVjMTIwYTlhMjA2OWUwODVjM2FhNTg5NGViM2FmYTAzMzgzOTcyMTQ1MGI1ZDg1Nzk5NzBkNWQyMTkyODBkYzBmY2UwYzk3Y2VkOGU5YTkzZWI4YTgwMjZjYzlmMmE1NjFiZDNiYjcwNzE1NzZkNjAyNjZlOTgzNGNmZDE4MzFiZmE1ZjI4MDcyYjA0ZDIzNWU4MGE1Zjk5YTg1MjJlMDVjY2VmZjJjZTVlNTljMDBiMjg2MjBkMmM4YTZjNzliYmEyY2I4ZCJ9"}',
      "X-Ratelimit-Limit",
      "50",
      "X-Ratelimit-Remaining",
      "23",
      "X-Ratelimit-Reset",
      "1663336800",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .patch(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents/63245b0e9c8ea5620b4a",
    {
      data: { title: "Batch" },
      permissions: ['read("any")', 'write("any")'],
    },
  )
  .reply(
    200,
    [
      zlib.gzipSync(
        JSON.stringify({
          title: "Batch",
          description: null,
          $id: "63245b0e9c8ea5620b4a",
          $createdAt: "2022-09-16T11:16:30.641+00:00",
          $updatedAt: "2022-09-16T13:34:28.447+00:00",
          $permissions: ['read("any")', 'update("any")', 'delete("any")'],
          $collectionId: "632455a55dc72e1aa016",
          $databaseId: "632455a0b8d017403ce9",
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "212",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:34:28 GMT",
      "Server",
      "Appwrite",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.010021209716797",
      "X-Ratelimit-Limit",
      "120",
      "X-Ratelimit-Remaining",
      "118",
      "X-Ratelimit-Reset",
      "1663335300",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .patch(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents/632456c5998583bcb6d3",
    {
      data: { title: "Batch" },
      permissions: ['read("any")', 'write("any")'],
    },
  )
  .reply(
    200,
    [
      zlib.gzipSync(
        JSON.stringify({
          title: "Batch",
          description: "test desc 2",
          $id: "632456c5998583bcb6d3",
          $createdAt: "2022-09-16T10:58:13.628+00:00",
          $updatedAt: "2022-09-16T13:34:28.475+00:00",
          $permissions: ['read("any")', 'update("any")', 'delete("any")'],
          $collectionId: "632455a55dc72e1aa016",
          $databaseId: "632455a0b8d017403ce9",
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "217",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:34:28 GMT",
      "Server",
      "Appwrite",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.022693157196045",
      "X-Ratelimit-Limit",
      "120",
      "X-Ratelimit-Remaining",
      "117",
      "X-Ratelimit-Reset",
      "1663335300",
      "Connection",
      "close",
    ],
  );
