import nock from "nock";
import zlib from "zlib";

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post("/v1/account/sessions/anonymous", {})
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          $id: "63247bcd90eb7497f07c",
          $createdAt: "2022-09-16T13:36:13.599+00:00",
          userId: "63247bcd8f8c1ae273c5",
          expire: "2023-09-16T13:36:13.593+00:00",
          provider: "anonymous",
          providerUid: "",
          providerAccessToken: "",
          providerAccessTokenExpiry: "",
          providerRefreshToken: "",
          ip: "159.146.41.20",
          osCode: "",
          osName: "",
          osVersion: "",
          clientType: "library",
          clientCode: "",
          clientName: "Node Fetch",
          clientVersion: "1.0",
          clientEngine: "",
          clientEngineVersion: "",
          deviceName: "",
          deviceBrand: "",
          deviceModel: "",
          countryCode: "tr",
          countryName: "Turkey",
          current: true,
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "301",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:36:13 GMT",
      "Server",
      "Appwrite",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5_legacy=eyJpZCI6IjYzMjQ3YmNkOGY4YzFhZTI3M2M1Iiwic2VjcmV0IjoiNDQwYzMxYTM0NTdkNDU5OTc5MmZkYjAzYTUyMzgxOTlkMmZkYzRhYTExZDkxMjI2MTkxMjcyMGM5NzkyMWE5YTZjYmI1NTVmNzIxNTBjMjlmMmU1ZjE1MzlhYTJkMmRmY2M5Zjg0MWM5MWM0Mjg4MDZiMDVjYzA5NWZmMjg3ZDJmMzhhNDJiYjM2Zjg3YzVlYzE3Nzc3YmFmMDI1NTE4MWRjZjdhZTc2ODlkYjc5ZWVlNTQyZTJiNjRhMWIyZTdmMzlhYjEyZjc3MzQzMDY2Njc4Y2JhNDhkYWQ3YzI2ZTY1Yzg2MzcxZjM3NDA4ZTJjOWM2MjFkMjMxOGVlZGIwNiJ9; expires=Sat, 16-Sep-2023 13:36:13 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5=eyJpZCI6IjYzMjQ3YmNkOGY4YzFhZTI3M2M1Iiwic2VjcmV0IjoiNDQwYzMxYTM0NTdkNDU5OTc5MmZkYjAzYTUyMzgxOTlkMmZkYzRhYTExZDkxMjI2MTkxMjcyMGM5NzkyMWE5YTZjYmI1NTVmNzIxNTBjMjlmMmU1ZjE1MzlhYTJkMmRmY2M5Zjg0MWM5MWM0Mjg4MDZiMDVjYzA5NWZmMjg3ZDJmMzhhNDJiYjM2Zjg3YzVlYzE3Nzc3YmFmMDI1NTE4MWRjZjdhZTc2ODlkYjc5ZWVlNTQyZTJiNjRhMWIyZTdmMzlhYjEyZjc3MzQzMDY2Njc4Y2JhNDhkYWQ3YzI2ZTY1Yzg2MzcxZjM3NDA4ZTJjOWM2MjFkMjMxOGVlZGIwNiJ9; expires=Sat, 16-Sep-2023 13:36:13 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly; samesite=None",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.023070096969604",
      "X-Fallback-Cookies",
      '{"a_session_6324555073b9706cb1f5":"eyJpZCI6IjYzMjQ3YmNkOGY4YzFhZTI3M2M1Iiwic2VjcmV0IjoiNDQwYzMxYTM0NTdkNDU5OTc5MmZkYjAzYTUyMzgxOTlkMmZkYzRhYTExZDkxMjI2MTkxMjcyMGM5NzkyMWE5YTZjYmI1NTVmNzIxNTBjMjlmMmU1ZjE1MzlhYTJkMmRmY2M5Zjg0MWM5MWM0Mjg4MDZiMDVjYzA5NWZmMjg3ZDJmMzhhNDJiYjM2Zjg3YzVlYzE3Nzc3YmFmMDI1NTE4MWRjZjdhZTc2ODlkYjc5ZWVlNTQyZTJiNjRhMWIyZTdmMzlhYjEyZjc3MzQzMDY2Njc4Y2JhNDhkYWQ3YzI2ZTY1Yzg2MzcxZjM3NDA4ZTJjOWM2MjFkMjMxOGVlZGIwNiJ9"}',
      "X-Ratelimit-Limit",
      "50",
      "X-Ratelimit-Remaining",
      "18",
      "X-Ratelimit-Reset",
      "1663336800",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents",
    {
      documentId: "unique()",
      data: { title: "Lorem" },
      permissions: ['read("any")', 'write("any")'],
    },
  )
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          title: "Lorem",
          $id: "63247bcdc14b72747fa8",
          $permissions: ['read("any")', 'update("any")', 'delete("any")'],
          $createdAt: "2022-09-16T13:36:13.791+00:00",
          $updatedAt: "2022-09-16T13:36:13.791+00:00",
          description: null,
          $collectionId: "632455a55dc72e1aa016",
          $databaseId: "632455a0b8d017403ce9",
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "208",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:36:13 GMT",
      "Server",
      "Appwrite",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.011168956756592",
      "X-Ratelimit-Limit",
      "120",
      "X-Ratelimit-Remaining",
      "119",
      "X-Ratelimit-Reset",
      "1663335420",
      "Connection",
      "close",
    ],
  );
