export const SWIZZLE_CODES = {
  SUCCESS: "SUCCESS",
  UNKNOWN_ERROR: "UNKNOWN_ERROR",
  SOURCE_PATH_NOT_FOUND: "SOURCE_PATH_NOT_FOUND",
  TARGET_PATH_NOT_FOUND: "TARGET_PATH_NOT_FOUND",
  SOURCE_PATH_NOT_A_FILE: "SOURCE_PATH_NOT_A_FILE",
  TARGET_ALREADY_EXISTS: "TARGET_ALREADY_EXISTS",
};
