packages:
  - "packages/*"
  - "examples/*"
  - "!examples/monorepo-*"
  - "!examples/with-nx"
  - "!documentation"
  - "!examples/blog-sveltekit-crud"
  - "!examples/blog-react-aria"
  - "!examples/with-nextjs-headless"
