packages:
  - "packages/*"
  - "examples/*"
  - "!examples/monorepo-*"
  - "!examples/with-nx"
  - "!documentation"
  - "!examples/blog-*"
  - "!examples/mern-dashboard-client"
  - "!examples/with-nextjs-headless"
  - "!examples/store"
