import nock from "nock";
import zlib from "zlib";

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post("/v1/account/sessions/anonymous", {})
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          $id: "63247c34e36601fbf48f",
          $createdAt: "2022-09-16T13:37:56.938+00:00",
          userId: "63247c34e28d28b259dd",
          expire: "2023-09-16T13:37:56.931+00:00",
          provider: "anonymous",
          providerUid: "",
          providerAccessToken: "",
          providerAccessTokenExpiry: "",
          providerRefreshToken: "",
          ip: "159.146.41.20",
          osCode: "",
          osName: "",
          osVersion: "",
          clientType: "library",
          clientCode: "",
          clientName: "Node Fetch",
          clientVersion: "1.0",
          clientEngine: "",
          clientEngineVersion: "",
          deviceName: "",
          deviceBrand: "",
          deviceModel: "",
          countryCode: "tr",
          countryName: "Turkey",
          current: true,
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "300",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:37:56 GMT",
      "Server",
      "Appwrite",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5_legacy=eyJpZCI6IjYzMjQ3YzM0ZTI4ZDI4YjI1OWRkIiwic2VjcmV0IjoiMjgyYTUyYWQwZjIzYzU2ZmMzOTU5YjhlOTMxYTBmM2VhODU2OWY4YzJlNmJjMDkxZDg4MTE2NzhiZDQ4ODUxOGQ1ODhiNmFiMGY1YTE0NjMwZjIwYWYyNmM2OGNmZDk3ZTMzNThhMjk0MTg3M2Q3YjkzZmJhMjExZjM0M2I1ODAxOGQxY2U5Yjk2MDgxZDAwYTVlYzQwNDk2ZTQ0OTk5Mzk1NGFlZmIwYTEyNDIxNjRlYmRkMGJlNDA5MjZmYTkyZmUzNjdjNzJlMzM3YWU5ZTY0YjM1N2UzZTg5ZWVmZTk4YjA4OTdmMDJiZjdmZmIyZjFjZWFmODBmYzYzNmIxYSJ9; expires=Sat, 16-Sep-2023 13:37:56 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5=eyJpZCI6IjYzMjQ3YzM0ZTI4ZDI4YjI1OWRkIiwic2VjcmV0IjoiMjgyYTUyYWQwZjIzYzU2ZmMzOTU5YjhlOTMxYTBmM2VhODU2OWY4YzJlNmJjMDkxZDg4MTE2NzhiZDQ4ODUxOGQ1ODhiNmFiMGY1YTE0NjMwZjIwYWYyNmM2OGNmZDk3ZTMzNThhMjk0MTg3M2Q3YjkzZmJhMjExZjM0M2I1ODAxOGQxY2U5Yjk2MDgxZDAwYTVlYzQwNDk2ZTQ0OTk5Mzk1NGFlZmIwYTEyNDIxNjRlYmRkMGJlNDA5MjZmYTkyZmUzNjdjNzJlMzM3YWU5ZTY0YjM1N2UzZTg5ZWVmZTk4YjA4OTdmMDJiZjdmZmIyZjFjZWFmODBmYzYzNmIxYSJ9; expires=Sat, 16-Sep-2023 13:37:56 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly; samesite=None",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.023267030715942",
      "X-Fallback-Cookies",
      '{"a_session_6324555073b9706cb1f5":"eyJpZCI6IjYzMjQ3YzM0ZTI4ZDI4YjI1OWRkIiwic2VjcmV0IjoiMjgyYTUyYWQwZjIzYzU2ZmMzOTU5YjhlOTMxYTBmM2VhODU2OWY4YzJlNmJjMDkxZDg4MTE2NzhiZDQ4ODUxOGQ1ODhiNmFiMGY1YTE0NjMwZjIwYWYyNmM2OGNmZDk3ZTMzNThhMjk0MTg3M2Q3YjkzZmJhMjExZjM0M2I1ODAxOGQxY2U5Yjk2MDgxZDAwYTVlYzQwNDk2ZTQ0OTk5Mzk1NGFlZmIwYTEyNDIxNjRlYmRkMGJlNDA5MjZmYTkyZmUzNjdjNzJlMzM3YWU5ZTY0YjM1N2UzZTg5ZWVmZTk4YjA4OTdmMDJiZjdmZmIyZjFjZWFmODBmYzYzNmIxYSJ9"}',
      "X-Ratelimit-Limit",
      "50",
      "X-Ratelimit-Remaining",
      "14",
      "X-Ratelimit-Reset",
      "1663336800",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents",
    {
      documentId: "unique()",
      data: { title: "Test 1" },
      permissions: ['read("any")', 'write("any")'],
    },
  )
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          title: "Test 1",
          $id: "63247c351f05e212bf3b",
          $permissions: ['read("any")', 'update("any")', 'delete("any")'],
          $createdAt: "2022-09-16T13:37:57.127+00:00",
          $updatedAt: "2022-09-16T13:37:57.127+00:00",
          description: null,
          $collectionId: "632455a55dc72e1aa016",
          $databaseId: "632455a0b8d017403ce9",
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "204",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:37:57 GMT",
      "Server",
      "Appwrite",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.010862112045288",
      "X-Ratelimit-Limit",
      "120",
      "X-Ratelimit-Remaining",
      "119",
      "X-Ratelimit-Reset",
      "1663335480",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents",
    {
      documentId: "unique()",
      data: { title: "Test 2" },
      permissions: ['read("any")', 'write("any")'],
    },
  )
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          title: "Test 2",
          $id: "63247c35208bb82dd2c8",
          $permissions: ['read("any")', 'update("any")', 'delete("any")'],
          $createdAt: "2022-09-16T13:37:57.133+00:00",
          $updatedAt: "2022-09-16T13:37:57.133+00:00",
          description: null,
          $collectionId: "632455a55dc72e1aa016",
          $databaseId: "632455a0b8d017403ce9",
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "206",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:37:57 GMT",
      "Server",
      "Appwrite",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.016963958740234",
      "X-Ratelimit-Limit",
      "120",
      "X-Ratelimit-Remaining",
      "118",
      "X-Ratelimit-Reset",
      "1663335480",
      "Connection",
      "close",
    ],
  );
