import nock from "nock";

nock("https://refine-fake-rest.pankod.com:443", { encodedQueryParams: true })
    .get("/posts")
    .query({ _end: "10", _order: "desc", _sort: "id", _start: "0" })
    .reply(
        200,
        [
            {
                id: 1000,
                title: "Et ratione rerum eos optio id nihil.",
                slug: "nihil-dignissimos-aut",
                content:
                    "Voluptatem cupiditate iusto excepturi quis minima. Aut neque architecto. Incidunt non porro. Minima itaque ipsa ut sed. Aut tenetur dignissimos ipsum. Soluta inventore sit rerum illum aut repellat minus. Illo autem enim nesciunt eos dicta pariatur. In ullam non vel placeat molestias vel soluta molestiae quasi. Qui porro rerum temporibus numquam ipsum voluptatem. Recusandae ut voluptate similique molestiae amet hic sit corporis voluptatibus.",
                category: { id: 19 },
                user: { id: 13 },
                status: "draft",
                createdAt: "2020-11-23T16:56:53.319Z",
                image: [],
                tags: [3],
                language: 3,
            },
            {
                id: 999,
                title: "Ad aut molestiae ex nostrum.",
                slug: "aut-dolores-ut",
                content:
                    "Quod est facere sed sit fuga in similique voluptatum. Porro voluptatem magni nihil alias est pariatur. Dignissimos molestiae debitis beatae consequatur. Quam similique repudiandae et eaque animi voluptate atque dolorem nostrum. Minima et deleniti quisquam aut aut. Reiciendis impedit ea et illo perferendis eos quos tempora est. Sunt eos nisi fugit. Aspernatur quisquam placeat praesentium eum. Dignissimos est commodi amet est asperiores suscipit asperiores et. Omnis architecto magnam corrupti.",
                category: { id: 15 },
                user: { id: 16 },
                status: "draft",
                createdAt: "2020-01-09T01:33:17.338Z",
                image: [],
                tags: [6, 1],
                language: 2,
            },
            {
                id: 998,
                title: "Doloribus quis sit enim non aut enim hic rerum quaerat.",
                slug: "ducimus-id-id",
                content:
                    "Animi dicta ut eum qui commodi exercitationem eius. Corrupti consequatur tenetur ut facere impedit minus. Dolor necessitatibus ad. Ut ipsam ut accusantium voluptatum. Commodi ut et. Aut explicabo tenetur in. Ullam illum similique natus. Inventore saepe dolorem explicabo. Consequatur sunt minus omnis optio et vero temporibus nihil nisi. Molestiae reprehenderit animi enim nostrum pariatur qui rerum consequatur.",
                category: { id: 22 },
                user: { id: 6 },
                status: "published",
                createdAt: "2021-05-05T14:14:59.295Z",
                image: [],
                tags: [5, 7],
                language: 3,
            },
            {
                id: 997,
                title: "Doloribus veritatis et quidem reiciendis eaque beatae voluptatem.",
                slug: "explicabo-ad-earum",
                content:
                    "Fugiat debitis dignissimos rerum. Sequi fuga et officiis. Ut iusto nulla est quasi labore enim cumque dolor. Quae harum omnis dolorem recusandae quo sunt nesciunt perspiciatis magnam. Aperiam est rerum aliquam provident dolores aliquid pariatur quo. Ut accusamus ipsa impedit recusandae eveniet saepe quia. Dolores fugiat voluptatem maiores suscipit sunt aut natus dicta. Rerum illo non consequatur. Odit doloribus fuga alias placeat sed et. Quam est quaerat ipsum non.",
                category: { id: 8 },
                user: { id: 6 },
                status: "published",
                createdAt: "2020-08-21T04:00:41.042Z",
                image: [],
                tags: [3, 6],
                language: 1,
            },
            {
                id: 996,
                title: "Magni aspernatur sit nesciunt.",
                slug: "consequatur-pariatur-ullam",
                content:
                    "Neque ducimus amet dignissimos cum dolorum praesentium debitis. Quidem dolorem voluptatum animi occaecati deleniti occaecati eius alias. Et neque ut at est sed qui debitis est ut. Eum voluptates minus quas sunt nesciunt perspiciatis non sit expedita. Totam dolorem aliquid assumenda. Accusamus excepturi laborum corporis aut consectetur. Ut corrupti sequi iure iste. Quae iure repellat perferendis aut aspernatur provident. Asperiores molestiae perspiciatis ut soluta facilis. Dolorum iste pariatur nam voluptatum aut facere consequatur.",
                category: { id: 7 },
                user: { id: 7 },
                status: "draft",
                createdAt: "2020-06-21T08:18:28.546Z",
                image: [],
                tags: [5, 1],
                language: 1,
            },
            {
                id: 995,
                title: "Nulla fugiat omnis.",
                slug: "et-accusantium-voluptatem",
                content:
                    "Iste molestiae incidunt sit quas possimus modi. Perspiciatis possimus exercitationem suscipit nisi dolores. Sunt qui excepturi doloribus est autem. Itaque laudantium nesciunt et eum doloribus. Quia possimus et iusto repellendus dolor iusto in ut. Distinctio non nostrum dolorum doloremque aut. Aut vel placeat doloribus. Exercitationem aut ullam. Facilis sed ipsum facere. Qui et et sunt animi eaque temporibus sunt consequatur.",
                category: { id: 49 },
                user: { id: 22 },
                status: "published",
                createdAt: "2021-03-31T06:44:45.635Z",
                image: [],
                tags: [4],
                language: 2,
            },
            {
                id: 994,
                title: "Reiciendis ut consequuntur neque.",
                slug: "alias-itaque-quae",
                content:
                    "Libero quis accusantium. Minus laboriosam vel modi labore est consequatur aperiam. Eligendi commodi eum beatae. Ad ab commodi aliquid enim consequatur nobis accusamus. Explicabo voluptatem voluptate. Et quidem et omnis sed nam dignissimos enim. Fugit alias saepe minus voluptatem optio dolor nulla sit. Nulla iusto occaecati harum fugiat. Sit consequatur sunt voluptas. Dolores adipisci rerum dolorum et et est vel.",
                category: { id: 11 },
                user: { id: 6 },
                status: "published",
                createdAt: "2020-02-14T17:46:30.519Z",
                image: [],
                tags: [9, 8],
                language: 1,
            },
            {
                id: 993,
                title: "Explicabo facilis quaerat et reprehenderit voluptatibus.",
                slug: "corporis-temporibus-magnam",
                content:
                    "Ipsam laudantium delectus quia. Ut voluptatem unde ut et qui iste. Voluptates qui ea temporibus deleniti ut. Nesciunt ratione dolorum quo et sed. Corrupti doloribus vitae consequuntur eveniet non voluptate natus repellat. Amet est sit inventore pariatur animi. Aliquam et mollitia rem. Ducimus recusandae voluptate. Non doloremque soluta nisi ducimus. Harum dolorum incidunt sunt.",
                category: { id: 6 },
                user: { id: 9 },
                status: "draft",
                createdAt: "2020-08-17T14:38:40.762Z",
                image: [],
                tags: [9],
                language: 2,
            },
            {
                id: 992,
                title: "Tenetur iusto sapiente minus perspiciatis magni quaerat fugiat ullam.",
                slug: "et-maxime-deserunt",
                content:
                    "Ut ut voluptatem occaecati explicabo ratione. Illum omnis rerum qui dolorem amet iusto et. Error qui molestiae distinctio. Quos beatae enim vel qui dolorum debitis. Consequatur commodi iste aut dicta. Quam voluptas sunt exercitationem consequuntur repellendus voluptatem. Ullam dolor eaque unde. Est tempora vero quas ea sed omnis. Explicabo explicabo modi eius sapiente omnis quis. Qui deleniti dolor non nisi autem quis.",
                category: { id: 29 },
                user: { id: 14 },
                status: "draft",
                createdAt: "2020-02-12T04:43:23.606Z",
                image: [],
                tags: [1, 7],
                language: 1,
            },
            {
                id: 991,
                title: "Doloribus quia id ratione minima autem accusantium dolores.",
                slug: "debitis-quaerat-quo",
                content:
                    "Sunt alias quam ut corporis et. Hic sint tempora voluptates voluptatem dolor nisi fugiat architecto in. Rerum est amet. Numquam nemo nostrum. Tempore nostrum et exercitationem quis est ut dolorum. Est mollitia est sunt. Voluptates alias autem qui eos quis est. Vel eum qui doloribus. Sed illo id nulla qui at rerum. Est quis tempore dicta expedita.",
                category: { id: 49 },
                user: { id: 33 },
                status: "draft",
                createdAt: "2019-10-19T05:14:10.208Z",
                image: [],
                tags: [2],
                language: 1,
            },
        ],
        [
            "Server",
            "nginx/1.17.10",
            "Date",
            "Tue, 18 May 2021 11:02:25 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "7903",
            "Connection",
            "close",
            "Vary",
            "Accept-Encoding",
            "X-Powered-By",
            "Express",
            "Vary",
            "Origin, Accept-Encoding",
            "Access-Control-Allow-Credentials",
            "true",
            "Cache-Control",
            "no-cache",
            "Pragma",
            "no-cache",
            "Expires",
            "-1",
            "Access-Control-Allow-Origin",
            "*",
            "X-Total-Count",
            "1000",
            "Access-Control-Expose-Headers",
            "X-Total-Count",
            "X-Content-Type-Options",
            "nosniff",
            "ETag",
            'W/"1edf-+x6WW1ricaY69iGdGbz4/GbNzjA"',
        ],
    );

nock("https://refine-fake-rest.pankod.com:443", {
    encodedQueryParams: true,
})
    .get("/posts")
    .query({ _end: "10", _order: "asc", _sort: "id", _start: "0" })
    .reply(
        200,
        [
            {
                id: 1,
                title: "Unde illum cupiditate ut.",
                slug: "temporibus-maxime-sed",
                content:
                    "Magni sunt eos omnis a magni rerum maxime animi maiores. Impedit quos reprehenderit eum rerum vitae magnam enim voluptatem. Consequatur ipsa natus doloribus enim odio et non repellat velit. Accusantium aut quia error nemo aliquam. Rem ut sit est neque recusandae est porro dolores voluptas. Omnis itaque eligendi voluptatem nulla doloribus. Reprehenderit qui esse aut distinctio consequatur dolorem nisi autem. Sint quam officiis magni. Error neque corporis dolor numquam aut sed dolorem provident. Architecto asperiores laudantium molestiae odio.",
                category: { id: 20 },
                user: { id: 50 },
                status: "published",
                createdAt: "2020-01-05T20:07:49.626Z",
                image: [],
                tags: [4],
                language: 1,
            },
            {
                id: 2,
                title: "Nihil ut ut vel ut veniam nesciunt ullam.",
                slug: "ipsa-inventore-et",
                content:
                    "Itaque iure eos nesciunt. Ut hic illum praesentium esse expedita omnis. Voluptas voluptate maiores occaecati corporis cum laboriosam nihil non earum. Perferendis laborum qui voluptas. Alias itaque et aut commodi magni est. Nam et recusandae quis autem totam. Rem consequuntur maiores error dolorem. Ex dolore ut numquam. Rem dignissimos aut. Architecto quas omnis deserunt.",
                category: { id: 45 },
                user: { id: 17 },
                status: "published",
                createdAt: "2020-07-26T18:23:20.263Z",
                image: [],
                tags: [1, 9],
                language: 1,
            },
            {
                id: 3,
                title: "Enim error veritatis quibusdam sed dignissimos quae.",
                slug: "quod-aut-quia",
                content:
                    "Magnam recusandae voluptas commodi ab excepturi rem nisi et. Voluptatibus et totam est modi. Unde repudiandae pariatur nemo qui voluptas enim repudiandae. Sit aliquam laboriosam quas quas consequatur. Non laudantium neque. Maiores laudantium pariatur nisi debitis non. Sit eius architecto sunt ipsum dolorem ut neque eaque. Cum quia sit fugiat totam tempore. Impedit ut quo sapiente sunt dolorum repellendus eos rerum ea. Deserunt id molestiae quis quis quia.",
                category: { id: 45 },
                user: { id: 37 },
                status: "draft",
                createdAt: "2019-10-22T04:50:19.177Z",
                image: [],
                tags: [1, 4],
                language: 1,
            },
            {
                id: 4,
                title: "Magnam architecto exercitationem iusto porro dolorem autem.",
                slug: "eos-ea-id",
                content:
                    "Quia et doloremque est et quia. Sit nesciunt aut facilis praesentium. Et ut nostrum ut voluptas. Ipsa ad doloremque rem. Saepe eum ea id facilis ea iure sit. Est laudantium facere sunt odio distinctio placeat eum nemo dolores. Voluptas neque culpa quod sint enim reprehenderit consectetur dolor repudiandae. Ut in ut ab perferendis. Commodi dicta sint voluptatem dolorum eum ut corporis et. Quae fugiat nam animi est dolorem id ut fuga.",
                category: { id: 45 },
                user: { id: 27 },
                status: "published",
                createdAt: "2019-09-30T03:01:07.946Z",
                image: [],
                tags: [9],
                language: 2,
            },
            {
                id: 5,
                title: "Repellat eligendi et temporibus consequuntur sapiente sit rem voluptatum expedita.",
                slug: "commodi-quis-quae",
                content:
                    "Iste fugiat nobis ut enim velit. Numquam tenetur debitis magnam veniam in consequatur. Nemo aut rerum officia dolorem eius enim modi nesciunt. Culpa necessitatibus delectus omnis eos aut voluptatem eos autem deserunt. Voluptatem culpa dolorem est veniam voluptas. Dolorem a non aliquam optio et alias aut illum voluptatum. Qui totam amet at impedit est. Eaque ipsam quam quis corporis minima aliquam ab et. Et neque fugit rem perferendis alias officiis ab maiores. Cupiditate possimus dicta et et accusantium qui provident est dolor.",
                category: { id: 28 },
                user: { id: 15 },
                status: "published",
                createdAt: "2020-08-13T05:03:37.189Z",
                image: [],
                tags: [6, 7],
                language: 2,
            },
            {
                id: 6,
                title: "Soluta aut ipsam molestias.",
                slug: "ea-numquam-excepturi",
                content:
                    "Est cum et. Modi at et laboriosam earum dicta molestiae necessitatibus pariatur. Ad delectus aut autem amet possimus ut eum. Et velit laborum qui sed quaerat omnis sapiente nihil. Illo ut rerum dolorem quibusdam reprehenderit. Maxime reprehenderit enim ad minus voluptatem non qui in. Illo odit qui. Aut nobis esse voluptatibus ad eum iure harum. Doloremque similique neque veritatis quia velit harum. Necessitatibus ratione rerum.",
                category: { id: 15 },
                user: { id: 47 },
                status: "published",
                createdAt: "2020-01-08T05:04:32.321Z",
                image: [],
                tags: [5, 4],
                language: 2,
            },
            {
                id: 7,
                title: "Dolorum et quod id est perspiciatis doloremque officia quisquam.",
                slug: "tempora-minus-voluptas",
                content:
                    "Et similique ut aut qui perferendis quod quia quis molestiae. Et sed enim optio laudantium ullam omnis vel eius facere. Adipisci ea est molestiae eum qui dolores deserunt harum. Laudantium et maiores facilis non corrupti aut dolorem. Ullam tempora beatae magni necessitatibus. Quos molestiae dolores dolorum omnis sed. Asperiores voluptas dolorem tempora qui quia voluptatibus officia officia excepturi. Aut laborum eos doloremque possimus tempore. Debitis praesentium veritatis sit architecto et. Earum eos non.",
                category: { id: 2 },
                user: { id: 29 },
                status: "published",
                createdAt: "2020-03-21T17:51:44.299Z",
                image: [],
                tags: [1],
                language: 1,
            },
            {
                id: 8,
                title: "Velit omnis quaerat eum et officiis aspernatur sit.",
                slug: "quas-rerum-consectetur",
                content:
                    "Et officiis vitae nihil numquam. Aspernatur eius enim distinctio omnis dolor voluptates dolores quibusdam. Reprehenderit voluptas ullam voluptas molestiae quia voluptatibus aut. Fuga perferendis magni et sed voluptatem repudiandae aperiam aut soluta. Rerum minus sit nulla excepturi quo quia qui esse est. Qui non non culpa. Ipsam in vero itaque sed occaecati. Incidunt voluptates ut perspiciatis nesciunt velit accusamus voluptatem similique. Culpa optio a eum quidem. Fuga sunt iste.",
                category: { id: 11 },
                user: { id: 17 },
                status: "published",
                createdAt: "2020-05-05T01:56:59.713Z",
                image: [],
                tags: [1],
                language: 1,
            },
            {
                id: 9,
                title: "Ratione voluptatem nam et.",
                slug: "culpa-enim-veniam",
                content:
                    "Accusamus aut ipsum qui nam asperiores sunt ut vel corporis. Placeat mollitia quo occaecati culpa. Corporis magni dolorem adipisci eveniet qui odio aut delectus. Delectus ipsa non. Quo qui repellendus harum omnis atque. Corrupti non molestias in consequatur blanditiis. Dicta occaecati iste consequatur velit nihil illo eligendi esse aut. Voluptas hic dolores iure autem dolores nihil repudiandae provident fugit. At magni cupiditate ut at necessitatibus perferendis et voluptatem cum. Soluta dolorem ex doloribus eos et praesentium est maiores.",
                category: { id: 28 },
                user: { id: 32 },
                status: "published",
                createdAt: "2020-09-04T21:51:45.744Z",
                image: [],
                tags: [1],
                language: 1,
            },
            {
                id: 10,
                title: "Quasi porro debitis asperiores qui aspernatur dolorem quia in.",
                slug: "voluptas-doloremque-dolorem",
                content:
                    "Voluptate aut magni eius. Dolorem nisi numquam neque. Maiores optio enim sapiente in modi sequi qui odio excepturi. In eligendi recusandae. Ut tempora exercitationem sint modi exercitationem. Nisi debitis quam voluptate eum et qui quod mollitia. Consequatur quisquam tenetur ut. Amet distinctio ut id laboriosam a. Autem necessitatibus ratione. Corrupti incidunt voluptas veritatis cum.",
                category: { id: 27 },
                user: { id: 36 },
                status: "draft",
                createdAt: "2021-01-02T01:15:05.481Z",
                image: [],
                tags: [6, 5],
                language: 1,
            },
        ],
        [
            "Server",
            "nginx/1.17.10",
            "Date",
            "Tue, 18 May 2021 11:02:25 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "8280",
            "Connection",
            "close",
            "Vary",
            "Accept-Encoding",
            "X-Powered-By",
            "Express",
            "Vary",
            "Origin, Accept-Encoding",
            "Access-Control-Allow-Credentials",
            "true",
            "Cache-Control",
            "no-cache",
            "Pragma",
            "no-cache",
            "Expires",
            "-1",
            "Access-Control-Allow-Origin",
            "*",
            "X-Total-Count",
            "1000",
            "Access-Control-Expose-Headers",
            "X-Total-Count",
            "X-Content-Type-Options",
            "nosniff",
            "ETag",
            'W/"2058-VevYwh3kIYYRtuxcqcNAYbwErvM"',
        ],
    );

nock("https://refine-fake-rest.pankod.com:443", {
    encodedQueryParams: true,
})
    .get("/posts")
    .query({
        _end: "10",
        _order: "desc",
        _sort: "id",
        _start: "0",
        "category.id": "1",
    })
    .reply(
        200,
        [
            {
                id: 960,
                title: "In itaque consequatur modi ut quas.",
                slug: "et-quam-aspernatur",
                content:
                    "Autem totam quas eius soluta. Quasi cum impedit voluptates et et quaerat nemo doloremque. Voluptatem consequuntur et hic. Consequuntur explicabo iste magni. Ut consequatur sint minus quia. Aut qui harum id totam quis ullam dolorem. Totam est est molestiae dolor harum sed eaque provident qui. Officiis eos et magnam cupiditate consequatur fugiat et enim iure. Perspiciatis odio itaque quia. Quod distinctio nisi et et odit molestiae cupiditate.",
                category: { id: 1 },
                user: { id: 30 },
                status: "published",
                createdAt: "2020-05-01T08:35:46.412Z",
                image: [],
                tags: [8, 7],
                language: 1,
            },
            {
                id: 959,
                title: "Repudiandae architecto est quis.",
                slug: "maiores-praesentium-inventore",
                content:
                    "Ea hic fugiat voluptate asperiores nesciunt cumque inventore deleniti. Doloribus quia beatae sapiente vel quia. Ut sed velit non quis sint omnis unde quos temporibus. Facilis quia hic ea omnis. Perferendis qui iusto sunt nulla expedita repellendus quos qui. Eum quos dolores adipisci exercitationem et. Omnis voluptates molestiae. Laborum sed amet ratione. Doloribus quia dolorem id nemo. Aut hic culpa natus fuga animi.",
                category: { id: 1 },
                user: { id: 13 },
                status: "draft",
                createdAt: "2020-05-23T15:07:22.583Z",
                image: [],
                tags: [2, 4],
                language: 1,
            },
            {
                id: 930,
                title: "Illum quaerat atque fugit pariatur dolor dicta magnam nulla.",
                slug: "est-ea-voluptatem",
                content:
                    "Commodi harum ipsum culpa. Cumque maiores sunt eum autem et corrupti. Sint neque quidem iure quibusdam perferendis aut. Aut inventore et quas dolores iure harum. Explicabo nulla nisi voluptas qui. Ut in ratione tempore. Quo qui sint odit ut nisi vel. Quasi doloribus quia qui inventore. Voluptate accusantium id qui in neque. Id rerum perferendis rerum libero repellat.",
                category: { id: 1 },
                user: { id: 50 },
                status: "published",
                createdAt: "2020-08-23T08:08:52.816Z",
                image: [],
                tags: [2, 1, 6],
                language: 1,
            },
            {
                id: 911,
                title: "Quia corporis soluta rem inventore unde voluptas quibusdam qui.",
                slug: "eius-et-eum",
                content:
                    "Nihil voluptatibus dignissimos mollitia velit aspernatur in aliquid rem. Eum culpa vero qui minus. Similique culpa voluptate ea nisi possimus non neque et placeat. Pariatur quo est iusto ea asperiores blanditiis asperiores. Explicabo ab qui tempore repellendus hic. Explicabo quo maiores vero. Libero et voluptatem recusandae amet minima praesentium. Tenetur nostrum ratione non est eos vel. Porro est unde recusandae quasi rem et voluptatem. Debitis sint vitae voluptates laborum.",
                category: { id: 1 },
                user: { id: 41 },
                status: "published",
                createdAt: "2019-08-04T03:51:26.414Z",
                image: [],
                tags: [1],
                language: 2,
            },
            {
                id: 845,
                title: "Quas nam autem dolor dolores.",
                slug: "aut-omnis-et",
                content:
                    "Debitis quisquam quia non. Perferendis aut aliquam rerum veritatis sunt eum vero et tempore. Voluptatem alias quo exercitationem quo alias vero veniam autem atque. Odit ut soluta est. Sed deleniti accusamus fuga soluta nam minima dolores sequi. Quisquam commodi quasi illum qui eius cumque ea dignissimos velit. Deleniti quo maiores sit. Dolores enim aut temporibus odio consequatur mollitia ducimus. Et et ratione magnam blanditiis. Enim recusandae hic autem debitis sed.",
                category: { id: 1 },
                user: { id: 42 },
                status: "published",
                createdAt: "2019-12-04T03:56:58.498Z",
                image: [],
                tags: [5],
                language: 3,
            },
            {
                id: 835,
                title: "Tempore quaerat consequatur.",
                slug: "debitis-id-qui",
                content:
                    "Voluptatibus aut sit ullam iusto hic vero magnam est. Eaque odio natus deserunt optio. Ipsum praesentium sit a nobis voluptate et enim ipsum. Et culpa ducimus ut ut architecto. Velit iure necessitatibus itaque molestiae voluptate enim natus perspiciatis. Necessitatibus dicta hic quo. Reiciendis consequatur hic voluptatem id odit ut debitis sequi. Voluptatibus quos qui. Rerum in ut voluptatem voluptatum tenetur quisquam sequi qui ad. Quae in suscipit beatae.",
                category: { id: 1 },
                user: { id: 46 },
                status: "published",
                createdAt: "2020-01-10T04:48:23.474Z",
                image: [],
                tags: [9],
                language: 1,
            },
            {
                id: 786,
                title: "Temporibus autem possimus molestiae ut possimus.",
                slug: "dolores-temporibus-ducimus",
                content:
                    "Omnis ipsam non pariatur soluta velit nisi saepe. Et error amet in sunt atque. Aut occaecati quas voluptatem. Nesciunt corrupti aperiam accusamus et voluptatem. Quasi dicta alias ut et quod recusandae possimus. Libero iure aperiam. Error alias deserunt. Sed qui eveniet in autem labore voluptates qui. Vel nulla amet provident. Rem labore sunt voluptas amet porro voluptas.",
                category: { id: 1 },
                user: { id: 4 },
                status: "published",
                createdAt: "2020-12-30T06:25:02.873Z",
                image: [],
                tags: [1],
                language: 1,
            },
            {
                id: 778,
                title: "Ipsum ut qui quis perspiciatis.",
                slug: "qui-ipsa-mollitia",
                content:
                    "Placeat dolore vel beatae eligendi totam dicta quam. Ut eos eligendi voluptatem et. Molestiae culpa beatae architecto ratione inventore pariatur excepturi quo ut. Provident et vitae ut. Minus animi quia eligendi. Exercitationem vel vel a eligendi. Temporibus voluptate sapiente natus. Suscipit necessitatibus voluptate ea doloremque commodi. Quia sit omnis amet rerum. Quae sint dicta accusamus nemo dolore.",
                category: { id: 1 },
                user: { id: 26 },
                status: "published",
                createdAt: "2021-02-27T21:23:12.465Z",
                image: [],
                tags: [2],
                language: 1,
            },
            {
                id: 683,
                title: "Aut voluptas exercitationem est doloribus vitae.",
                slug: "eveniet-sed-quia",
                content:
                    "Assumenda libero et voluptate. Quis in blanditiis. Provident nisi consectetur similique accusamus atque voluptatem non recusandae. Incidunt assumenda autem qui illo eaque voluptate quo laboriosam. Voluptatibus officiis fugiat veritatis nemo totam repellat molestiae asperiores tempore. Illum modi inventore rem ex. Eos reprehenderit ut dolore quisquam. Aut nemo ducimus nobis eaque fuga est. Fuga voluptatem autem exercitationem modi. Architecto ea sed odit numquam.",
                category: { id: 1 },
                user: { id: 6 },
                status: "draft",
                createdAt: "2019-08-30T01:41:30.885Z",
                image: [],
                tags: [3],
                language: 2,
            },
            {
                id: 614,
                title: "Quisquam ipsum eveniet.",
                slug: "voluptates-quia-et",
                content:
                    "Odit laudantium odio quasi autem alias. Nobis impedit optio veritatis earum unde. Minima sed dolor deleniti repellendus. Similique non eum vel et quibusdam itaque id et. Quae maiores sit voluptas. Facere aut accusantium a aliquam. Aut adipisci sed et a. Laudantium debitis dolores. Ea eum nostrum doloremque. Facilis quo corrupti maxime aliquam rerum cumque voluptatem.",
                category: { id: 1 },
                user: { id: 33 },
                status: "draft",
                createdAt: "2021-02-28T09:50:52.798Z",
                image: [],
                tags: [1, 5],
                language: 3,
            },
        ],
        [
            "Server",
            "nginx/1.17.10",
            "Date",
            "Tue, 18 May 2021 11:02:26 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "7740",
            "Connection",
            "close",
            "Vary",
            "Accept-Encoding",
            "X-Powered-By",
            "Express",
            "Vary",
            "Origin, Accept-Encoding",
            "Access-Control-Allow-Credentials",
            "true",
            "Cache-Control",
            "no-cache",
            "Pragma",
            "no-cache",
            "Expires",
            "-1",
            "Access-Control-Allow-Origin",
            "*",
            "X-Total-Count",
            "18",
            "Access-Control-Expose-Headers",
            "X-Total-Count",
            "X-Content-Type-Options",
            "nosniff",
            "ETag",
            'W/"1e3c-4aYlhAIKNFvfDy+r/7oHTtXWEEw"',
        ],
    );

nock("https://refine-fake-rest.pankod.com:443", {
    encodedQueryParams: true,
})
    .get("/posts")
    .query({
        _end: "10",
        _order: "asc",
        _sort: "id",
        _start: "0",
        "category.id": "1",
    })
    .reply(
        200,
        [
            {
                id: 67,
                title: "Alias voluptatem debitis accusamus dolores.",
                slug: "minima-amet-ut",
                content:
                    "Nisi distinctio non totam eaque hic animi atque. Ut est aspernatur est. Inventore est voluptatem vero laboriosam at maiores autem. Eius dolore saepe ut sunt qui voluptatem temporibus et. Provident commodi nostrum sequi et id quasi cupiditate architecto. Nisi totam est vitae nihil ab omnis. Quod maxime officia ipsum. Accusamus dolores illum repellat ducimus omnis eveniet amet. Ut et ab voluptatem autem ea. Unde optio perspiciatis iste delectus.",
                category: { id: 1 },
                user: { id: 32 },
                status: "draft",
                createdAt: "2019-08-06T22:59:40.947Z",
                image: [],
                tags: [1, 3, 5],
                language: 1,
            },
            {
                id: 202,
                title: "Natus ut magni officia enim animi.",
                slug: "et-tempore-pariatur",
                content:
                    "Ea non enim atque quas ipsam excepturi. Mollitia qui occaecati. Repellendus voluptatibus repudiandae adipisci voluptas iure vel tempora neque. Quia quis ex voluptatibus id. Quo maxime nesciunt quisquam et ut et neque. Sed sed et odio architecto quas facilis laudantium. Quidem hic ipsa quas. Aut quia illo voluptatibus possimus iusto libero eos. Et facere iusto. Modi vel alias iusto asperiores repudiandae officia quia dolor.",
                category: { id: 1 },
                user: { id: 33 },
                status: "published",
                createdAt: "2020-05-22T21:33:12.619Z",
                image: [],
                tags: [6],
                language: 1,
            },
            {
                id: 203,
                title: "Rerum molestiae aut recusandae quia aspernatur et.",
                slug: "sit-et-rerum",
                content:
                    "Aperiam ut quis officia sunt. Magni delectus placeat. Dolore nostrum quod officiis ex beatae labore. Assumenda hic voluptatem corporis molestias inventore aliquid voluptatem. Laudantium sint culpa. Et voluptatem iure eaque a consequuntur. In libero sit dolor aperiam et iste sed voluptatem. Voluptatem aut illo voluptates. Magni minima quia. Et placeat quia doloribus.",
                category: { id: 1 },
                user: { id: 32 },
                status: "draft",
                createdAt: "2020-10-16T18:14:24.288Z",
                image: [],
                tags: [1, 5],
                language: 1,
            },
            {
                id: 305,
                title: "Dolores tempora doloremque quia dolorum quaerat qui odio at quis.",
                slug: "eum-corrupti-molestiae",
                content:
                    "Aut minima eos voluptas vitae. Consequatur rerum atque error rerum dolorem qui. Qui fugit earum ipsa labore saepe dolores cum nobis atque. Quam quia esse fugiat cum voluptatem possimus. Est harum harum rem. Sint quis ut doloremque. Qui quia ut rem. Fugiat aperiam autem maxime vitae quam ea. Et exercitationem amet quasi. Modi similique quos aut necessitatibus laudantium magni modi.",
                category: { id: 1 },
                user: { id: 18 },
                status: "draft",
                createdAt: "2020-07-06T10:33:32.514Z",
                image: [],
                tags: [7],
                language: 3,
            },
            {
                id: 334,
                title: "Explicabo ut quia.",
                slug: "sed-pariatur-nihil",
                content:
                    "Laboriosam ut aut voluptatem aliquam reprehenderit cum eaque. Saepe temporibus recusandae. Quisquam at est nulla ad. Tempora qui quis quas. Ratione quibusdam quis rem non voluptate vero quaerat sunt est. Excepturi veniam asperiores harum ut eum atque. Est rem mollitia. Mollitia cupiditate consequatur dignissimos laborum reiciendis ea. Velit qui voluptatem. Voluptas suscipit natus et ab voluptatem.",
                category: { id: 1 },
                user: { id: 1 },
                status: "draft",
                createdAt: "2021-04-04T03:26:15.969Z",
                image: [],
                tags: [5, 2, 4],
                language: 2,
            },
            {
                id: 373,
                title: "Veniam quasi quibusdam perferendis.",
                slug: "tenetur-quisquam-minima",
                content:
                    "Praesentium molestiae consequatur ducimus ullam. Omnis enim libero explicabo voluptatem nemo. At voluptate ut dolores perferendis consequatur aut maxime illo autem. Tempore consequatur iusto et. Et amet nam quia. Libero aspernatur nesciunt. Officia eum aliquid deleniti. Corrupti ex earum saepe quis accusamus. Iusto nihil sunt odio ipsa qui possimus officia. Rerum est ratione inventore voluptatum est et nam libero.",
                category: { id: 1 },
                user: { id: 35 },
                status: "published",
                createdAt: "2020-05-01T04:25:47.071Z",
                image: [],
                tags: [4],
                language: 3,
            },
            {
                id: 376,
                title: "Unde ipsum vero alias aut aperiam enim cupiditate ab necessitatibus.",
                slug: "consequatur-quos-explicabo",
                content:
                    "Nesciunt quos autem. Illo soluta aspernatur ut. Omnis aperiam id est ducimus. Aliquid inventore sint vel eius perspiciatis at illo molestiae. Tenetur nisi aut ab. Qui odio non accusamus ut voluptates asperiores in eveniet. Laudantium et voluptatem est labore non sunt. Pariatur qui dolores. At maxime id ipsum corrupti. Maxime aperiam mollitia maxime unde quisquam deserunt ut.",
                category: { id: 1 },
                user: { id: 21 },
                status: "draft",
                createdAt: "2021-05-07T02:12:28.312Z",
                image: [],
                tags: [8],
                language: 1,
            },
            {
                id: 476,
                title: "Omnis et et ad quo laudantium dolores.",
                slug: "sed-et-similique",
                content:
                    "Hic omnis ut alias. Eveniet iusto doloremque doloribus. Libero quis deleniti impedit. Nisi occaecati et nihil qui voluptatum. Quas ut itaque. Ut et nihil esse quibusdam molestiae non et corporis. Odit sit nulla eos. Nobis perspiciatis voluptate dolor occaecati earum veniam fugit vel. Corporis et voluptatem recusandae et. Optio sed occaecati.",
                category: { id: 1 },
                user: { id: 44 },
                status: "draft",
                createdAt: "2020-01-15T17:45:56.231Z",
                image: [],
                tags: [9, 1],
                language: 3,
            },
            {
                id: 614,
                title: "Quisquam ipsum eveniet.",
                slug: "voluptates-quia-et",
                content:
                    "Odit laudantium odio quasi autem alias. Nobis impedit optio veritatis earum unde. Minima sed dolor deleniti repellendus. Similique non eum vel et quibusdam itaque id et. Quae maiores sit voluptas. Facere aut accusantium a aliquam. Aut adipisci sed et a. Laudantium debitis dolores. Ea eum nostrum doloremque. Facilis quo corrupti maxime aliquam rerum cumque voluptatem.",
                category: { id: 1 },
                user: { id: 33 },
                status: "draft",
                createdAt: "2021-02-28T09:50:52.798Z",
                image: [],
                tags: [1, 5],
                language: 3,
            },
            {
                id: 683,
                title: "Aut voluptas exercitationem est doloribus vitae.",
                slug: "eveniet-sed-quia",
                content:
                    "Assumenda libero et voluptate. Quis in blanditiis. Provident nisi consectetur similique accusamus atque voluptatem non recusandae. Incidunt assumenda autem qui illo eaque voluptate quo laboriosam. Voluptatibus officiis fugiat veritatis nemo totam repellat molestiae asperiores tempore. Illum modi inventore rem ex. Eos reprehenderit ut dolore quisquam. Aut nemo ducimus nobis eaque fuga est. Fuga voluptatem autem exercitationem modi. Architecto ea sed odit numquam.",
                category: { id: 1 },
                user: { id: 6 },
                status: "draft",
                createdAt: "2019-08-30T01:41:30.885Z",
                image: [],
                tags: [3],
                language: 2,
            },
        ],
        [
            "Server",
            "nginx/1.17.10",
            "Date",
            "Tue, 18 May 2021 11:02:26 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "7502",
            "Connection",
            "close",
            "Vary",
            "Accept-Encoding",
            "X-Powered-By",
            "Express",
            "Vary",
            "Origin, Accept-Encoding",
            "Access-Control-Allow-Credentials",
            "true",
            "Cache-Control",
            "no-cache",
            "Pragma",
            "no-cache",
            "Expires",
            "-1",
            "Access-Control-Allow-Origin",
            "*",
            "X-Total-Count",
            "18",
            "Access-Control-Expose-Headers",
            "X-Total-Count",
            "X-Content-Type-Options",
            "nosniff",
            "ETag",
            'W/"1d4e-neP3qW9KGxHknNPc+mt2yWbHl2o"',
        ],
    );
