import nock from "nock";

nock("https://readmin-fake-rest.pankod.com:443", { encodedQueryParams: true })
    .get("/posts")
    .query({ _end: "10", _order: "desc", _sort: "id", _start: "0" })
    .reply(
        200,
        [
            {
                title:
                    "Ducimus amet beatae optio blanditiis dolore fugit aut quam.g",
                id: 1000,
            },
            {
                id: 999,
                title: "Aut commodi dolorum qui sed quasi est sed.",
                slug: "dignissimos-ullam-nihil",
                content:
                    "Voluptatem aperiam qui dolor unde accusantium ex saepe. Iusto ut voluptas saepe excepturi. Qui impedit repellendus et qui similique. Voluptatum eligendi et beatae quisquam animi aut autem. Suscipit ab voluptatem est sit saepe atque. Labore labore temporibus ut. Optio magni cumque molestiae dolores aut ut architecto quis. Beatae corrupti at et quaerat aut est impedit porro. Voluptas dolores excepturi eos error velit voluptate repellat itaque. Pariatur quo magni illo sed dolorem sunt.",
                categoryId: 37,
                status: "draft",
                userId: 19,
                tags: [2, 32, 50],
                image: [],
            },
            {
                id: 998,
                title: "Vero incidunt dolorum neque enim facere minima sint.",
                slug: "aut-modi-esse",
                content:
                    "Atque non hic aspernatur amet amet voluptas. Ullam aut illum. Ut quia assumenda ducimus. Nam quod porro repellat. Et enim facere. Et a ducimus cupiditate et sunt modi et atque. Consectetur quia eius nesciunt qui omnis libero autem. Odio atque illo et. Commodi possimus aut laboriosam veniam quis beatae. Minima perferendis at quia sapiente omnis itaque.",
                categoryId: 43,
                status: "active",
                userId: 36,
                tags: [11, 33, 50],
                image: [],
            },
            {
                id: 997,
                title: "Quod amet quos ut.",
                slug: "hic-non-doloremque",
                content:
                    "Et magnam dolorum id. Et eos et nulla dolores veritatis. Officiis placeat occaecati. Maxime dolore dolor consequatur autem. Id et et ad sit nobis. Autem repellat aut. Maiores modi fuga reprehenderit in deleniti voluptates. Numquam voluptate quod cupiditate. Sed quis quisquam fugit dolor. Dolor explicabo sed repellat non hic ad distinctio esse exercitationem.",
                categoryId: 5,
                status: "active",
                userId: 9,
                tags: [5, 21, 42],
                image: [],
            },
            {
                id: 996,
                title: "Magni quidem amet eos.",
                slug: "numquam-magnam-rerum",
                content:
                    "Totam sunt officiis eius. Impedit inventore qui impedit dolor atque sed ullam. Omnis unde quia eaque cupiditate delectus. Ut blanditiis voluptatibus minus. Non molestias facilis. Eum corrupti natus. Animi magnam quia eum pariatur laboriosam enim qui recusandae. Voluptatum necessitatibus sequi corporis velit fugiat assumenda ullam labore. Perferendis accusantium possimus autem molestiae. Est aut dolorem blanditiis aspernatur cupiditate quaerat sint.",
                categoryId: 28,
                status: "active",
                userId: 25,
                tags: [0, 21, 43],
                image: [],
            },
            {
                id: 995,
                title:
                    "Aspernatur velit quibusdam inventore accusantium voluptatem assumenda placeat recusandae vel.",
                slug: "laboriosam-laboriosam-atque",
                content:
                    "Soluta dignissimos iure. Aliquid minus enim natus voluptates. Voluptatem asperiores alias sapiente perferendis omnis. Quas iusto voluptas et aut et dolores mollitia corrupti. Qui nihil adipisci aperiam suscipit numquam et eos voluptatem. Placeat quo laudantium dicta vel. Et perspiciatis sed est et debitis eius ut doloribus sequi. Adipisci fugit dolorem qui perferendis dolor ipsa. Tempora id dicta fugit porro velit exercitationem. Accusamus fuga magnam.",
                categoryId: 9,
                status: "active",
                userId: 1,
                tags: [13, 33, 50],
                image: [],
            },
            {
                id: 994,
                title: "Voluptatem expedita occaecati.",
                slug: "dolores-accusantium-officia",
                content:
                    "Recusandae illum aut praesentium impedit assumenda dolorem. Ut vero laboriosam sunt vel sed. Commodi possimus quos nam veritatis minus unde at. Ut saepe minima nihil et vel quidem. Qui ea amet. Qui explicabo repudiandae porro dolorem. Accusantium molestias voluptatem ducimus est delectus atque et nesciunt quia. Et quos blanditiis minima natus est facere nam autem aliquam. Assumenda eaque quam excepturi facilis laudantium omnis qui adipisci. Soluta blanditiis cupiditate quis placeat est vel voluptatem quia corrupti.",
                categoryId: 15,
                status: "active",
                userId: 22,
                tags: [4, 34, 40],
                image: [],
            },
            {
                id: 993,
                title:
                    "Totam voluptatum minus et dolorem nostrum iure qui explicabo.",
                slug: "est-neque-quia",
                content:
                    "Itaque distinctio quia. Est nesciunt mollitia sit expedita id ea. Eos aut quis quas. Sit enim minima unde dolor quos in. Sit corrupti voluptas dolor. Eos dolor ratione optio. Quo laudantium vitae. Quasi eveniet animi. Unde optio laboriosam sed quasi amet sunt qui natus. Aliquam alias laborum repellat ut commodi ut exercitationem odit perspiciatis.",
                categoryId: 47,
                status: "draft",
                userId: 45,
                tags: [17, 23, 40],
                image: [],
            },
            {
                id: 992,
                title: "Quidem quidem facere.",
                slug: "debitis-voluptatem-quia",
                content:
                    "Ut voluptas voluptas facere hic explicabo ut non. Voluptas dolor tenetur et laudantium et aut atque. Enim ea magnam labore cupiditate. Omnis ea ut dolores omnis aut quo doloremque est adipisci. Eum odio enim. Ut nihil iure ullam sint aut. Quae nesciunt quibusdam voluptatum. Voluptatem illo sed fugiat est reprehenderit tenetur tenetur. Aperiam dignissimos sed facere maxime. Quasi velit praesentium aut quae et sit cumque.",
                categoryId: 48,
                status: "active",
                userId: 4,
                tags: [6, 33, 42],
                image: [],
            },
            {
                id: 991,
                title: "Fugit quia nemo quas porro aut quo laborum aut.",
                slug: "ratione-eos-esse",
                content:
                    "Nulla eligendi dolorem cumque qui expedita iusto eum. Tempore accusantium sed deserunt ad voluptatem. Sunt et eum eum ipsam praesentium eveniet. Et aspernatur perspiciatis cupiditate distinctio iusto. Unde ab est ea eligendi autem exercitationem rerum numquam. Molestiae et provident et nulla quae aliquam. Ab modi quod unde vel voluptatem autem id. Ut sed odit laborum explicabo non et consequuntur omnis. Sed dolor qui laboriosam molestias fugiat numquam. Qui voluptates sed sint minima nostrum maiores minus modi eos.",
                categoryId: 41,
                status: "draft",
                userId: 1,
                tags: [16, 23, 44],
                image: [],
            },
        ],
        [
            "Server",
            "nginx/1.17.10",
            "Date",
            "Tue, 30 Mar 2021 11:13:15 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "6430",
            "Connection",
            "close",
            "Vary",
            "Accept-Encoding",
            "X-Powered-By",
            "Express",
            "Vary",
            "Origin, Accept-Encoding",
            "Access-Control-Allow-Credentials",
            "true",
            "Cache-Control",
            "no-cache",
            "Pragma",
            "no-cache",
            "Expires",
            "-1",
            "X-Total-Count",
            "1000",
            "Access-Control-Expose-Headers",
            "X-Total-Count",
            "X-Content-Type-Options",
            "nosniff",
            "ETag",
            'W/"191e-ytsUDJ6yej+chsf9wbRdqCfFNhQ"',
        ],
    );

nock("https://readmin-fake-rest.pankod.com:443", {
    encodedQueryParams: true,
})
    .get("/posts")
    .query({ _end: "10", _order: "asc", _sort: "id", _start: "0" })
    .reply(
        200,
        [
            {
                id: 1,
                title:
                    "Deleniti et quasi architecto hic quam et tempora vero quo.",
                slug: "nobis-aut-eligendi",
                content:
                    "Accusantium sed nam odio ut non qui. Maxime quaerat sed ducimus corrupti consequatur. Facere numquam ut reprehenderit quaerat quia. Recusandae quibusdam asperiores atque architecto quod praesentium sit non. Aut neque repellat veniam veritatis qui et vel alias debitis. Amet eius omnis dolores. Sint sed magni. Dolor eius maiores asperiores et. Et modi illum eius quisquam maxime at vel qui. Sit dolore officiis aliquid quia labore.",
                categoryId: 20,
                status: "active",
                userId: 16,
                tags: [15, 36, 46],
                image: [],
            },
            {
                id: 2,
                title:
                    "Ea possimus ullam voluptatum blanditiis fugiat odit molestiae et.",
                slug: "excepturi-qui-sed",
                content:
                    "Omnis maiores qui voluptas nihil. Quo natus eum hic aut. Id sit sed sed ut. Ex temporibus autem omnis est quas pariatur. Itaque perferendis sequi nobis dolor rerum quidem qui nostrum nihil. Et debitis eveniet et. Perspiciatis id nobis ut sint voluptatem numquam tempora eveniet. Eius qui quidem temporibus qui explicabo impedit dolor. Fugiat itaque pariatur assumenda molestiae. Et deserunt quibusdam ut tenetur id officia et molestias facilis.",
                categoryId: 21,
                status: "draft",
                userId: 29,
                tags: [9, 34, 43],
                image: [],
            },
            {
                id: 3,
                title: "Debitis sit porro doloribus.",
                slug: "natus-ut-saepe",
                content:
                    "Officiis nostrum consectetur eum repudiandae vitae. Commodi vel atque et eos. Atque voluptas enim et soluta aut ut et natus. Consequatur est excepturi et veritatis rerum non laboriosam consequuntur. Aut dolorum maxime. Deleniti voluptas autem omnis non. Perspiciatis et sunt culpa et. Aperiam eveniet quae qui non explicabo facilis magnam unde non. Voluptatem id nemo ut. Laudantium dolor animi dolores fugit a.",
                categoryId: 11,
                status: "active",
                userId: 21,
                tags: [8, 25, 40],
                image: [],
            },
            {
                id: 4,
                title: "Aut a neque alias non et.",
                slug: "quisquam-omnis-sequi",
                content:
                    "Modi corrupti voluptatem omnis suscipit. Unde veritatis dolores rerum rerum ducimus voluptatem. Debitis magni enim culpa iste. Eum atque accusamus quia rerum facilis eveniet quae enim. Tempore ad est iusto rem rerum et. Impedit maxime optio autem occaecati natus voluptas. Temporibus quibusdam sunt ea excepturi doloremque impedit dolores. Accusamus perspiciatis esse et asperiores recusandae ut modi voluptatem. Esse sunt quidem dolores eius blanditiis molestiae. Non aut delectus sunt eos ut nobis optio quia rerum.",
                categoryId: 24,
                status: "draft",
                userId: 27,
                tags: [10, 32, 49],
                image: [],
            },
            {
                id: 5,
                title:
                    "Facilis ab ab non et reiciendis corporis velit eveniet aspernatur.",
                slug: "dolores-iure-fugiat",
                content:
                    "Enim sed similique velit aut vitae ratione nostrum. Similique repellendus ex labore architecto modi. Itaque harum quis quidem. Aut fuga quod. Sed voluptas commodi. Fugiat quas reiciendis eaque aliquid enim sint. Consectetur est occaecati. Itaque voluptatibus veritatis illo ea voluptate. Ab sed sit minima sit dignissimos. Quam ullam fuga est.",
                categoryId: 49,
                status: "draft",
                userId: 13,
                tags: [4, 39, 46],
                image: [],
            },
            {
                id: 6,
                title: "Quidem quae deleniti.",
                slug: "optio-quibusdam-vel",
                content:
                    "Id voluptatem perferendis dolorem corrupti accusamus. Similique facere temporibus consequatur. Fugit libero et consectetur sequi consectetur quam aut quia. Laboriosam voluptas qui consequatur similique omnis quo odio autem. Eius quod sunt sed nesciunt temporibus. Tempora distinctio optio sed quis. Et perspiciatis magni itaque. Sint laboriosam ex qui sed asperiores sint molestias unde eius. Atque dolorum ut sit et harum necessitatibus aut et. Hic nihil animi sint similique aperiam asperiores consequatur molestias.",
                categoryId: 4,
                status: "active",
                userId: 35,
                tags: [7, 35, 40],
                image: [],
            },
            {
                id: 7,
                title: "Quae ut aut ducimus iste.",
                slug: "vitae-dolorum-fuga",
                content:
                    "Rerum vel nisi et debitis aut voluptatem voluptatibus quidem. Quibusdam eligendi autem. Est nostrum voluptatem quos nemo. Est blanditiis laboriosam vero. Quia qui fugiat corrupti non necessitatibus accusantium beatae ea. Ipsum et maiores sunt sunt omnis enim. Corporis inventore minima ea quo voluptates. Rerum rerum explicabo sint excepturi. Sed nam qui unde. Est sapiente tenetur aut.",
                categoryId: 12,
                status: "active",
                userId: 17,
                tags: [17, 21, 49],
                image: [],
            },
            {
                id: 8,
                title: "Autem excepturi aut cumque molestias.",
                slug: "dolor-aut-qui",
                content:
                    "Rerum eos id aspernatur culpa corrupti consequatur. Debitis et inventore sint numquam sunt eum incidunt provident. Qui asperiores quae exercitationem laboriosam non qui dolorem. Consequatur assumenda delectus aspernatur iure. Et omnis sit voluptatem excepturi neque ad. Fuga omnis necessitatibus iste natus et. Ut ad cum reprehenderit voluptas non. Numquam asperiores dolor vero. Quia blanditiis recusandae nam autem rerum. Autem ab ab.",
                categoryId: 15,
                status: "active",
                userId: 39,
                tags: [12, 40, 48],
                image: [],
            },
            {
                id: 9,
                title: "Omnis iure aut fuga rerum.",
                slug: "reprehenderit-ut-et",
                content:
                    "Eos nostrum voluptate et eaque sed molestiae. Dolores ut laboriosam sunt veritatis autem. Quia aut aperiam ut. Porro expedita quaerat a laborum aut quia. Sed sapiente consequuntur eveniet et sed. Et ad quam ex necessitatibus. In quia porro tempora aut adipisci quis. Est nulla aperiam eveniet nostrum qui qui fugit ipsam. Aliquid rem est non. Recusandae perspiciatis rerum et quasi sunt placeat quo hic.",
                categoryId: 12,
                status: "active",
                userId: 16,
                tags: [18, 20, 45],
                image: [],
            },
            {
                id: 10,
                title: "Iste aut aut laborum magnam sit.",
                slug: "id-ut-rerum",
                content:
                    "Perferendis et provident minima numquam dolor labore maxime quia. Tempora qui aut unde nam tempora sed consequatur consequuntur. Praesentium consequatur totam unde. Architecto placeat similique beatae eos. Ut blanditiis ut tenetur. Qui ullam eos commodi. Laboriosam quo et laborum animi expedita autem quibusdam occaecati provident. In vero nesciunt. Inventore rerum quis. Natus aperiam soluta et eos voluptas consequatur.",
                categoryId: 5,
                status: "draft",
                userId: 36,
                tags: [0, 20, 40],
                image: [],
            },
        ],
        [
            "Server",
            "nginx/1.17.10",
            "Date",
            "Tue, 30 Mar 2021 11:19:26 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "6894",
            "Connection",
            "close",
            "Vary",
            "Accept-Encoding",
            "X-Powered-By",
            "Express",
            "Vary",
            "Origin, Accept-Encoding",
            "Access-Control-Allow-Credentials",
            "true",
            "Cache-Control",
            "no-cache",
            "Pragma",
            "no-cache",
            "Expires",
            "-1",
            "X-Total-Count",
            "1000",
            "Access-Control-Expose-Headers",
            "X-Total-Count",
            "X-Content-Type-Options",
            "nosniff",
            "ETag",
            'W/"1aee-mUjPJeVC0rB42/qYwr/fWMtw6ps"',
        ],
    );

nock("https://readmin-fake-rest.pankod.com:443", {
    encodedQueryParams: true,
})
    .get("/posts")
    .query({
        _end: "10",
        _order: "desc",
        _sort: "id",
        _start: "0",
        categoryId: "1",
    })
    .reply(
        200,
        [
            {
                id: 926,
                title: "Pariatur voluptatem voluptatem eos ducimus ex.",
                slug: "nostrum-non-adipisci",
                content:
                    "Enim beatae ab fuga numquam odit quia et quibusdam. Magnam asperiores expedita sunt aut. Minus qui dolor ex in vel ratione molestias. Velit architecto aperiam quibusdam ipsam. Consectetur harum et soluta aut impedit quo sit iure molestiae. Repellendus sint ut rem omnis. Earum dignissimos non eum nemo sed ipsa. Dolorem odio nesciunt non nam molestias officia. Ratione quis nemo ea doloremque ut dolores impedit quia dignissimos. Magnam officiis qui.",
                categoryId: 1,
                status: "active",
                userId: 35,
                tags: [5, 37, 48],
                image: [],
            },
            {
                id: 919,
                title: "Quas repellendus dignissimos deleniti.",
                slug: "mollitia-quia-amet",
                content:
                    "Dolor consequuntur sunt repudiandae quis iste labore. Aut recusandae excepturi temporibus suscipit et sed doloribus. Ut et voluptatem ut illum aperiam illum repudiandae voluptatem. Iste vero accusantium explicabo temporibus eum alias quia modi. Quis ut perferendis quas consectetur dolorem ut labore adipisci. Optio sunt et quia sint autem est non. Sit eum ea nobis architecto maiores earum. Ipsam iusto qui quisquam nemo. Sed libero explicabo commodi rerum aut quas. Quia voluptas nobis et.",
                categoryId: 1,
                status: "draft",
                userId: 12,
                tags: [20, 31, 48],
                image: [],
            },
            {
                id: 889,
                title: "Et recusandae nihil assumenda cum qui.",
                slug: "enim-reprehenderit-nisi",
                content:
                    "Enim nulla voluptatum aut incidunt necessitatibus. Eligendi ea molestiae qui non saepe maxime aut. Nulla eos cupiditate consequatur et est qui voluptatem. Distinctio perferendis libero ducimus ut iste voluptatem. Sequi adipisci ratione facere fugit. Alias quam sunt ipsa rem aut deserunt. Repellendus expedita tempore. Cumque maxime rem sint vel voluptate sed sed totam. Sit tempora repellat voluptatibus iste animi nihil fugit molestias animi. Reprehenderit blanditiis eaque sapiente labore.",
                categoryId: 1,
                status: "active",
                userId: 2,
                tags: [18, 33, 47],
                image: [],
            },
            {
                id: 882,
                title: "Maxime ab sapiente.",
                slug: "adipisci-magnam-pariatur",
                content:
                    "Sint nihil libero hic. Sint voluptatum rerum. Ex ad ex. Nulla voluptatibus cum ut animi laboriosam consequatur facere nesciunt commodi. Esse autem eum a minima consequatur voluptatem iusto incidunt. Reiciendis qui et ad voluptatum autem necessitatibus officiis. Ducimus ipsam ab quia qui et possimus aliquid laborum. Consectetur hic quis porro sed. Aliquid nulla voluptate id modi earum quasi earum doloremque sed. Aut aperiam sit.",
                categoryId: 1,
                status: "active",
                userId: 18,
                tags: [9, 32, 50],
                image: [],
            },
            {
                id: 853,
                title: "Voluptatem est molestiae.",
                slug: "adipisci-voluptas-ea",
                content:
                    "At modi neque dignissimos quia ipsa maiores ducimus. Ex qui beatae. Qui velit dolores quas. Tempore eligendi soluta molestiae consequatur dignissimos dolor ipsa nobis iste. Magni sed quod dolorum delectus. Rerum error et ut vel aliquam quam recusandae. Mollitia omnis molestiae pariatur rerum suscipit quia vitae minima quod. Eos distinctio dolorem molestiae. Non eligendi corporis asperiores excepturi id consequatur. Nisi inventore possimus.",
                categoryId: 1,
                status: "active",
                userId: 18,
                tags: [0, 39, 40],
                image: [],
            },
            {
                id: 778,
                title:
                    "Dolorem voluptas nihil voluptas qui voluptas odit atque dolorem.",
                slug: "nisi-voluptatibus-numquam",
                content:
                    "Iusto corrupti molestias. Omnis ut qui nulla autem quia cum. In quia vitae. Esse laboriosam aut at. Exercitationem voluptas modi earum voluptas. Nesciunt ut distinctio reiciendis ut. Ut ipsum ut nemo aspernatur. Totam magnam modi culpa et quam vel asperiores. Ut dolorem hic molestiae et aut est quidem. Accusantium aut omnis.",
                categoryId: 1,
                status: "draft",
                userId: 37,
                tags: [7, 32, 47],
                image: [],
            },
            {
                id: 707,
                title: "Distinctio laudantium molestias dignissimos.",
                slug: "consequuntur-vitae-natus",
                content:
                    "Corrupti libero quibusdam earum amet tenetur perspiciatis nihil. Sed culpa nam consequuntur et assumenda et culpa sed consequuntur. Dolor quo qui. Dolor corrupti et. Unde eos voluptate magni alias qui quisquam facilis. Pariatur maxime est reprehenderit dolore. Ipsa dicta porro vel distinctio voluptatem cupiditate omnis doloribus quia. Sint tempore non sed aut enim. Ea nesciunt assumenda. Numquam assumenda blanditiis aut est beatae sunt error.",
                categoryId: 1,
                status: "draft",
                userId: 27,
                tags: [13, 30, 45],
                image: [],
            },
            {
                id: 640,
                title: "At ut atque autem tenetur.",
                slug: "ipsa-nobis-voluptatem",
                content:
                    "Modi voluptatem at. Commodi suscipit qui quo et. Delectus quod voluptatem incidunt aliquam dolor dignissimos architecto. Aut officia id magni assumenda. Voluptatibus accusantium sed. Corporis aut aut voluptatem occaecati impedit natus neque minima. Ut non laudantium est sunt quas id reprehenderit. Qui voluptatem consequatur cupiditate magni. Sequi et dolores doloribus id. Cumque minima magnam ullam sit sapiente ea nulla ut.",
                categoryId: 1,
                status: "active",
                userId: 23,
                tags: [7, 30, 46],
                image: [],
            },
            {
                id: 619,
                title: "Et fuga quos ipsam nesciunt ut quam modi magnam.",
                slug: "ipsum-est-illum",
                content:
                    "Ab vitae magnam delectus. Vitae fuga eos sint earum. Expedita quo quod ratione dolorem. Sunt consequatur libero nisi exercitationem eveniet nihil iure aut eligendi. Accusamus aspernatur commodi. At eaque ipsa nam reiciendis fugiat quod tempora molestiae. Commodi odio voluptates quia non. Veritatis sint et rerum fuga quo. Vitae cum et eligendi sint sed qui dolore sed cumque. Impedit vel quasi dolor facilis minima nihil.",
                categoryId: 1,
                status: "active",
                userId: 29,
                tags: [3, 33, 42],
                image: [],
            },
            {
                id: 522,
                title: "Ut qui amet rerum dignissimos voluptatem temporibus.",
                slug: "veniam-ut-sapiente",
                content:
                    "Voluptas corporis beatae voluptas consectetur vero sunt sint molestiae minima. Voluptatum sint natus perferendis facere et dignissimos qui. Voluptatibus est aspernatur fugiat ut. Suscipit odit quibusdam. Molestiae magnam ad et nobis amet. Neque voluptatem repellat nobis iusto nesciunt sit fugit quidem nemo. Nemo a omnis. Qui temporibus dolor eos et vel tenetur neque ut blanditiis. Commodi voluptatem praesentium ut assumenda quas laudantium ad sit delectus. Natus eos qui et dolor expedita assumenda voluptas.",
                categoryId: 1,
                status: "draft",
                userId: 45,
                tags: [18, 24, 47],
                image: [],
            },
        ],
        [
            "Server",
            "nginx/1.17.10",
            "Date",
            "Tue, 30 Mar 2021 11:22:02 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "7089",
            "Connection",
            "close",
            "Vary",
            "Accept-Encoding",
            "X-Powered-By",
            "Express",
            "Vary",
            "Origin, Accept-Encoding",
            "Access-Control-Allow-Credentials",
            "true",
            "Cache-Control",
            "no-cache",
            "Pragma",
            "no-cache",
            "Expires",
            "-1",
            "X-Total-Count",
            "20",
            "Access-Control-Expose-Headers",
            "X-Total-Count",
            "X-Content-Type-Options",
            "nosniff",
            "ETag",
            'W/"1bb1-UMfljhVSFDBeBCxWgBHocrvYPlg"',
        ],
    );

nock("https://readmin-fake-rest.pankod.com:443", {
    encodedQueryParams: true,
})
    .get("/posts")
    .query({
        _end: "10",
        _order: "asc",
        _sort: "id",
        _start: "0",
        categoryId: "1",
    })
    .reply(
        200,
        [
            {
                id: 61,
                title:
                    "Error illum rerum mollitia officiis repellat quia repudiandae expedita provident.",
                slug: "deserunt-eos-qui",
                content:
                    "Voluptas soluta aliquid beatae dolores sed illum magni consequuntur. Laborum provident ipsam porro dicta at vel animi beatae. Corrupti et vel vel vel culpa quibusdam. A eaque dolorem officiis. Illum et consequatur aut veritatis recusandae. Ea vitae voluptatum praesentium. Qui repellendus suscipit delectus. Aspernatur voluptatum id ut dicta assumenda ratione ipsa rerum vel. Qui odio rem. Incidunt qui error aut inventore ullam voluptates modi.",
                categoryId: 1,
                status: "draft",
                userId: 25,
                tags: [19, 26, 45],
                image: [],
            },
            {
                id: 66,
                title:
                    "Similique officia ducimus quia quia et hic ullam nam dolorem.",
                slug: "et-aperiam-consequatur",
                content:
                    "Doloribus quis maxime vero cum tempora. Itaque fugiat fuga enim vitae deleniti. Repudiandae reiciendis corrupti repudiandae ad tenetur. A provident suscipit enim iusto. Animi consequatur est sint facere quia nostrum expedita. Mollitia voluptas nesciunt vero accusamus quis aut tempore est et. Repudiandae assumenda et perspiciatis aut dicta veritatis dolorem ipsa accusantium. Consequuntur mollitia soluta id. Sapiente rerum suscipit sapiente ullam distinctio delectus doloremque qui similique. Ad maxime ratione.",
                categoryId: 1,
                status: "active",
                userId: 23,
                tags: [16, 25, 44],
                image: [],
            },
            {
                id: 220,
                title: "Consectetur dolore ex minus ex sunt.",
                slug: "nihil-nesciunt-fuga",
                content:
                    "Rerum ut doloremque tempora eos dolorem placeat. Pariatur ut corporis. Sed molestias quasi molestias et sit minima et et. Qui quis iure sunt. Saepe qui aperiam autem enim corrupti consequatur optio. Aliquam ex ullam dolores. Minus dignissimos voluptatum quo et culpa voluptas veniam. Deserunt cupiditate neque culpa. Qui dignissimos molestiae sint veritatis asperiores id. Praesentium qui aliquid.",
                categoryId: 1,
                status: "active",
                userId: 4,
                tags: [12, 39, 41],
                image: [],
            },
            {
                id: 225,
                title:
                    "Tempora qui fuga rerum nemo doloribus omnis corporis laboriosam.",
                slug: "et-reiciendis-et",
                content:
                    "Reiciendis aut ut ab fuga odit cumque ut magnam. Ad optio tempore eos eius ratione nemo. Expedita id natus nesciunt. Dolore ut itaque tenetur iusto aut. Accusantium est fugiat quis consequatur culpa quaerat fuga. Tempora commodi harum ea magnam non dolore ut blanditiis. Occaecati tempore sed qui excepturi quibusdam neque repellat sed. Molestiae consequatur maxime eligendi porro omnis. Voluptas laboriosam voluptatum qui. Minus aut autem dolores est.",
                categoryId: 1,
                status: "draft",
                userId: 49,
                tags: [1, 27, 47],
                image: [],
            },
            {
                id: 275,
                title: "Error nulla non consequatur.",
                slug: "totam-pariatur-sit",
                content:
                    "Accusantium non accusamus autem odit numquam. Inventore facere laudantium distinctio totam sint. Est totam velit officiis assumenda voluptatem. Doloremque quis cumque aut. Est repudiandae voluptatem magnam autem asperiores sed nisi necessitatibus. Velit porro et repellendus sit assumenda unde ea. Aut omnis aut animi minus aut assumenda atque. Debitis sed et voluptates blanditiis corporis eum distinctio at. Esse et reprehenderit vel numquam temporibus ut itaque. Quibusdam perspiciatis cumque voluptatem et rerum pariatur eligendi minus.",
                categoryId: 1,
                status: "draft",
                userId: 38,
                tags: [15, 39, 49],
                image: [],
            },
            {
                id: 300,
                title:
                    "Eum hic et omnis aut magnam occaecati voluptatum culpa.",
                slug: "enim-saepe-praesentium",
                content:
                    "Expedita rem sit aliquid autem sit. Officia error consequuntur dolore nam quod quasi necessitatibus eos. Rem expedita dolorem vitae porro voluptatem ut quia accusamus. Ut qui vel. Excepturi rem eius provident quas incidunt. Omnis tempora totam repellat voluptatem quo fugiat accusamus et voluptate. Unde excepturi aut explicabo aut. Dolor deleniti nobis sunt praesentium aperiam aut corporis dolorum in. Culpa iusto occaecati deleniti delectus et facilis. Nulla ea iste.",
                categoryId: 1,
                status: "active",
                userId: 39,
                tags: [9, 38, 44],
                image: [],
            },
            {
                id: 378,
                title:
                    "Repellendus incidunt occaecati voluptas perspiciatis deserunt nihil iure eius accusamus.",
                slug: "dolores-perspiciatis-ducimus",
                content:
                    "Repellat eum porro velit. Et qui nisi voluptas sit. Est quia ipsam. Et quibusdam velit illo perspiciatis. Et fuga reprehenderit ut praesentium. Atque doloribus quia at quas molestiae qui numquam. Ab inventore quaerat. Occaecati et et est debitis molestiae et est totam voluptatem. Laborum laborum fugit esse odit in eaque. Ducimus molestiae eveniet et ad et et in eos.",
                categoryId: 1,
                status: "active",
                userId: 5,
                tags: [1, 31, 46],
                image: [],
            },
            {
                id: 426,
                title: "Consequatur a quod at sunt.",
                slug: "qui-possimus-aut",
                content:
                    "Molestias impedit est dolores occaecati atque aut consequatur ipsam. Architecto ipsum repudiandae distinctio eligendi explicabo sapiente aut. Perspiciatis enim harum sint. Veritatis similique voluptatem. Fugit quia quos aspernatur et. Quis pariatur sequi ut architecto quaerat dolores. Enim commodi qui. Tenetur aperiam suscipit nam illo hic molestias in harum. Ut iure aut consectetur et explicabo ea voluptatum. Ea nisi explicabo molestias quis.",
                categoryId: 1,
                status: "draft",
                userId: 27,
                tags: [12, 38, 47],
                image: [],
            },
            {
                id: 500,
                title: "Quam vel itaque consequatur.",
                slug: "voluptatem-debitis-asperiores",
                content:
                    "Quo molestias est dignissimos optio quo. Perferendis exercitationem aut est unde tempore magni et sit. Voluptatem consequatur nisi porro quasi reprehenderit explicabo beatae et voluptatem. Ut fugiat a. Quis omnis in deserunt vitae. Delectus quas dicta quis accusantium id nostrum. Doloremque fugit excepturi enim dolore quasi quis est eveniet. Voluptatem quo et nesciunt porro quia iste et ad sunt. Non minus repudiandae ipsa consequuntur et tempore. Quia ab ut.",
                categoryId: 1,
                status: "draft",
                userId: 13,
                tags: [14, 32, 42],
                image: [],
            },
            {
                id: 501,
                title:
                    "Nam molestiae consequatur quis molestias quod enim culpa.",
                slug: "aut-excepturi-ut",
                content:
                    "Cumque placeat est dolorem animi suscipit. Laborum et molestias. Explicabo consequuntur ipsa quidem. Ab unde est ut cupiditate. Quo totam ut est. Debitis perferendis aut quis optio libero aut. Ex ad facere et beatae cum. Nesciunt facere sit non est excepturi ad ut perspiciatis enim. Velit est dicta. Sequi sequi magni quas.",
                categoryId: 1,
                status: "draft",
                userId: 18,
                tags: [17, 31, 47],
                image: [],
            },
        ],
        [
            "Server",
            "nginx/1.17.10",
            "Date",
            "Tue, 30 Mar 2021 11:24:45 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "7184",
            "Connection",
            "close",
            "Vary",
            "Accept-Encoding",
            "X-Powered-By",
            "Express",
            "Vary",
            "Origin, Accept-Encoding",
            "Access-Control-Allow-Credentials",
            "true",
            "Cache-Control",
            "no-cache",
            "Pragma",
            "no-cache",
            "Expires",
            "-1",
            "X-Total-Count",
            "20",
            "Access-Control-Expose-Headers",
            "X-Total-Count",
            "X-Content-Type-Options",
            "nosniff",
            "ETag",
            'W/"1c10-zGG2tTBuJ2RTNKdtkLcNh/Yu24U"',
        ],
    );
