export const packageMap: Record<string, string> = {
    "@pankod/refine-core": "RefineCore",
    "@pankod/refine-react-router-v6": "RefineReactRouterV6",
    "@pankod/refine-antd": "RefineAntd",
    "@pankod/refine-mui": "RefineMui",
    "@pankod/refine-mantine": "RefineMantine",
    "@pankod/refine-chakra-ui": "RefineChakra",
    "@pankod/refine-simple-rest": "RefineSimpleRest",
    "@pankod/refine-react-hook-form": "RefineReactHookForm",
    "@pankod/refine-react-table": "RefineReactTable",
    "@pankod/refine-inferencer/antd": "RefineAntdInferencer",
    "@pankod/refine-inferencer/mui": "RefineMuiInferencer",
    "@pankod/refine-inferencer/mantine": "RefineMantineInferencer",
    "@pankod/refine-inferencer/chakra-ui": "RefineChakraInferencer",
};
