import {
  IconSun,
  IconMoonStars,
  IconLanguage,
  IconChevronRight,
  IconChevronLeft,
  IconSelector,
  IconChevronDown,
  IconFilter,
  IconX,
  IconCheck,
  IconMoodSmile,
  IconList,
  IconCategory,
  IconUsers,
  IconDashboard,
  IconPower,
  IconLogout,
  IconMenu2,
  IconMoon,
  IconLayoutSidebarLeftCollapse,
  IconLayoutSidebarLeftExpand,
} from "@tabler/icons-react";

const TablerScope = {
  TablerIcons: {
    IconSun,
    IconMoonStars,
    IconLanguage,
    IconChevronRight,
    IconChevronLeft,
    IconSelector,
    IconChevronDown,
    IconFilter,
    IconX,
    IconCheck,
    IconMoodSmile,
    IconList,
    IconCategory,
    IconUsers,
    IconDashboard,
    IconPower,
    IconLogout,
    IconMenu2,
    IconMoon,
    IconLayoutSidebarLeftCollapse,
    IconLayoutSidebarLeftExpand,
  },
};

export default TablerScope;
