import {
    IconSun,
    IconMoonStars,
    IconLanguage,
    IconChevronRight,
    IconChevronLeft,
    IconSelector,
    IconChevronDown,
    IconFilter,
    IconX,
    IconCheck,
    IconMoodSmile,
    IconList,
    IconCategory,
    IconUsers,
    IconDashboard,
    IconLogout,
    IconMenu2,
    IconMoon,
    IconLayoutSidebarLeftCollapse,
    IconLayoutSidebarLeftExpand,
} from "@tabler/icons";

const TablerScope = {
    TablerIcons: {
        IconSun,
        IconMoonStars,
        IconLanguage,
        IconChevronRight,
        IconChevronLeft,
        IconSelector,
        IconChevronDown,
        IconFilter,
        IconX,
        IconCheck,
        IconMoodSmile,
        IconList,
        IconCategory,
        IconUsers,
        IconDashboard,
        IconLogout,
        IconMenu2,
        IconMoon,
        IconLayoutSidebarLeftCollapse,
        IconLayoutSidebarLeftExpand,
    },
};

export default TablerScope;
