import nock from "nock";

nock("https://dev001.na-dev-engine.altogic.com:443", {
    encodedQueryParams: true,
})
    .get("/post/613a25eb65f2050012410a41")
    .reply(
        200,
        {
            _id: "613a25eb65f2050012410a41",
            createdAt: "2021-09-09T15:19:07.122Z",
            updatedAt: "2021-09-10T11:57:13.152Z",
            title: "test",
            categoryId: "61373e585d65d30019e2b0a2",
            status: "draft",
            content: "adasdad",
        },
        [
            "Date",
            "Mon, 13 Sep 2021 12:23:23 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "204",
            "Connection",
            "close",
            "X-Powered-By",
            "Altogic",
            "Access-Control-Allow-Origin",
            "*",
            "Surrogate-Control",
            "no-store",
            "Cache-Control",
            "no-store, no-cache, must-revalidate, proxy-revalidate",
            "Pragma",
            "no-cache",
            "Expires",
            "0",
            "Access-Control-Expose-Headers",
            "X-Service-Id, X-Duration, X-Validated-Duration, Content-Length, Content-Type, Content-Disposition, X-Powered-By",
            "X-Service-Id",
            "61373d5361cf2c001a1e27f8",
            "X-Duration",
            "5",
            "X-Validated-Duration",
            "7",
            "Strict-Transport-Security",
            "max-age=15724800; includeSubDomains",
        ],
    );
