import { useContext, useEffect } from "react";
import { useParsed, useRefineContext } from "@hooks";
import { useLegacyAuthContext } from "@contexts/auth";
import { DocumentTitleContext } from "@contexts/document-title";
import { generateDefaultDocumentTitle } from "@definitions/helpers";

export const RouteChangeHandler: React.FC = () => {
    const { checkAuth } = useLegacyAuthContext();
    const { updateTitle } = useContext(DocumentTitleContext);

    const { params, pathname, resource, action } = useParsed();
    const {
        options: { generateDocumentTitle },
    } = useRefineContext();

    useEffect(() => {
        checkAuth?.().catch(() => false);

        if (generateDocumentTitle && action && resource) {
            const id = params?.id;
            const autoGeneratedTitle = generateDefaultDocumentTitle(
                resource,
                action,
                id,
            );

            if (typeof generateDocumentTitle === "function") {
                updateTitle(
                    generateDocumentTitle({
                        resource,
                        action,
                        autoGeneratedTitle,
                        params: params ?? {},
                    }),
                    pathname ?? "",
                    0,
                );
            } else {
                updateTitle(autoGeneratedTitle, pathname ?? "", 0);
            }
        }
    }, [pathname]);

    return null;
};
