import { Metadata } from "next";
import React, { Suspense } from "react";
import { RefineContext } from "./_refine_context";
import { AntdRegistry } from "@ant-design/nextjs-registry";

export const metadata: Metadata = {
    title: "Refine",
    description: "Generated by create refine app",
    icons: {
        icon: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AntdRegistry>
                    <Suspense>
                        <RefineContext>{children}</RefineContext>
                    </Suspense>
                </AntdRegistry>
            </body>
        </html>
    );
}
