import nock from "nock";
import zlib from "zlib";

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post("/v1/account/sessions/anonymous", {})
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          $id: "63247b1255f99d4b9357",
          $createdAt: "2022-09-16T13:33:06.357+00:00",
          userId: "63247b1254bdf190f761",
          expire: "2023-09-16T13:33:06.352+00:00",
          provider: "anonymous",
          providerUid: "",
          providerAccessToken: "",
          providerAccessTokenExpiry: "",
          providerRefreshToken: "",
          ip: "159.146.41.20",
          osCode: "",
          osName: "",
          osVersion: "",
          clientType: "library",
          clientCode: "",
          clientName: "Node Fetch",
          clientVersion: "1.0",
          clientEngine: "",
          clientEngineVersion: "",
          deviceName: "",
          deviceBrand: "",
          deviceModel: "",
          countryCode: "tr",
          countryName: "Turkey",
          current: true,
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "299",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:33:06 GMT",
      "Server",
      "Appwrite",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5_legacy=eyJpZCI6IjYzMjQ3YjEyNTRiZGYxOTBmNzYxIiwic2VjcmV0IjoiMGQ1NTZlYzIzMGE1OTdmNWY4NjNmM2ZlY2Q5NWMzYjQwOTRiYzk1YzAyMjA2OTY5YTJlNDk3NTNlMjBhYTU5YjNjYzY4MTNlMTUxMGNlNzg5OWM2MGY2Y2I1MThhYWVhNDQ4ZDcwZDhhMzllYzMzNjA2MjZiMTc5NjZkMmRjZWI0M2Q2MGJmNWRjNWNmMTBkZTk0ZDgwNDFjMzk4NGRhMTNiZjk5M2JlYmM4MTkzOWY3NDE4MmQzMzUyYzhmYjhhNDNjNDUxYzc0ZjViZGRhNjA2NDljZmYwZGQ2ODQ1NTkzMTRjZjI5Nzk4MDkxMTNiMGZhNzY0MzUwMzM4ZmI1NiJ9; expires=Sat, 16-Sep-2023 13:33:06 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5=eyJpZCI6IjYzMjQ3YjEyNTRiZGYxOTBmNzYxIiwic2VjcmV0IjoiMGQ1NTZlYzIzMGE1OTdmNWY4NjNmM2ZlY2Q5NWMzYjQwOTRiYzk1YzAyMjA2OTY5YTJlNDk3NTNlMjBhYTU5YjNjYzY4MTNlMTUxMGNlNzg5OWM2MGY2Y2I1MThhYWVhNDQ4ZDcwZDhhMzllYzMzNjA2MjZiMTc5NjZkMmRjZWI0M2Q2MGJmNWRjNWNmMTBkZTk0ZDgwNDFjMzk4NGRhMTNiZjk5M2JlYmM4MTkzOWY3NDE4MmQzMzUyYzhmYjhhNDNjNDUxYzc0ZjViZGRhNjA2NDljZmYwZGQ2ODQ1NTkzMTRjZjI5Nzk4MDkxMTNiMGZhNzY0MzUwMzM4ZmI1NiJ9; expires=Sat, 16-Sep-2023 13:33:06 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly; samesite=None",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.021300077438354",
      "X-Fallback-Cookies",
      '{"a_session_6324555073b9706cb1f5":"eyJpZCI6IjYzMjQ3YjEyNTRiZGYxOTBmNzYxIiwic2VjcmV0IjoiMGQ1NTZlYzIzMGE1OTdmNWY4NjNmM2ZlY2Q5NWMzYjQwOTRiYzk1YzAyMjA2OTY5YTJlNDk3NTNlMjBhYTU5YjNjYzY4MTNlMTUxMGNlNzg5OWM2MGY2Y2I1MThhYWVhNDQ4ZDcwZDhhMzllYzMzNjA2MjZiMTc5NjZkMmRjZWI0M2Q2MGJmNWRjNWNmMTBkZTk0ZDgwNDFjMzk4NGRhMTNiZjk5M2JlYmM4MTkzOWY3NDE4MmQzMzUyYzhmYjhhNDNjNDUxYzc0ZjViZGRhNjA2NDljZmYwZGQ2ODQ1NTkzMTRjZjI5Nzk4MDkxMTNiMGZhNzY0MzUwMzM4ZmI1NiJ9"}',
      "X-Ratelimit-Limit",
      "50",
      "X-Ratelimit-Remaining",
      "25",
      "X-Ratelimit-Reset",
      "1663336800",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .patch(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents/63245b02205ba8cec507",
    {
      data: { title: "Updated" },
      permissions: ['read("any")', 'write("any")'],
    },
  )
  .reply(
    200,
    [
      zlib.gzipSync(
        JSON.stringify({
          title: "Updated",
          description: null,
          $id: "63245b02205ba8cec507",
          $createdAt: "2022-09-16T11:16:18.132+00:00",
          $updatedAt: "2022-09-16T13:33:06.550+00:00",
          $permissions: ['read("any")', 'update("any")', 'delete("any")'],
          $collectionId: "632455a55dc72e1aa016",
          $databaseId: "632455a0b8d017403ce9",
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "211",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:33:06 GMT",
      "Server",
      "Appwrite",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.010154008865356",
      "X-Ratelimit-Limit",
      "120",
      "X-Ratelimit-Remaining",
      "119",
      "X-Ratelimit-Reset",
      "1663335240",
      "Connection",
      "close",
    ],
  );
