import { IResourceItem } from "@contexts/resource";
import { Action } from "./actions";

export type IGenerateDocumentTitleCallback = (options: {
    resource?: IResourceItem;
    action?: Action;
    params: Record<string, string | undefined>;
    autoGeneratedTitle: string;
}) => string;
export type IGenerateDocumentTitle =
    | undefined
    | boolean
    | IGenerateDocumentTitleCallback;
