export const team = [
    {
        name: "Civan Özseyhan",
        avatar: "/about/images/team-avatars/civan.png",
        avatar2x: "/about/images/team-avatars/civan2x.png",
        role1: "Co-Founder",
        role2: "CEO",
    },
    {
        name: "Ömer Aplak",
        avatar: "/about/images/team-avatars/omer.png",
        avatar2x: "/about/images/team-avatars/omer2x.png",
        role1: "Co-Founder",
        role2: "CTO",
    },
    {
        name: "Eren Erkalkan",
        avatar: "/about/images/team-avatars/eren.png",
        avatar2x: "/about/images/team-avatars/eren2x.png",
        role1: "Co-Founder",
        role2: "Head of Product",
    },
    {
        name: "Batuhan Özgür Özdemir",
        avatar: "/about/images/team-avatars/batuhan.png",
        avatar2x: "/about/images/team-avatars/batuhan2x.png",
        role1: "Tech Lead",
    },
    {
        name: "Ali Emir Şen",
        avatar: "/about/images/team-avatars/ali.png",
        avatar2x: "/about/images/team-avatars/ali2x.png",
        role1: "Frontend Team Lead",
    },
    {
        name: "Yıldıray Ünlü",
        avatar: "/about/images/team-avatars/yildiray.png",
        avatar2x: "/about/images/team-avatars/yildiray2x.png",
        role1: "Backend Team Lead",
    },
    {
        name: "Salih Özdemir",
        avatar: "/about/images/team-avatars/salih.png",
        avatar2x: "/about/images/team-avatars/salih2x.png",
        role1: "Software Developer",
    },
    {
        name: "Alican Erdurmaz",
        avatar: "/about/images/team-avatars/alican.png",
        avatar2x: "/about/images/team-avatars/alican2x.png",
        role1: "Software Developer",
    },
    {
        name: "Necati Ozmen",
        avatar: "/about/images/team-avatars/necati.png",
        avatar2x: "/about/images/team-avatars/necati2x.png",
        role1: "Head of Content",
    },
    {
        name: "Recep Kütük",
        avatar: "/about/images/team-avatars/recep.png",
        avatar2x: "/about/images/team-avatars/recep2x.png",
        role1: "Senior Product Designer",
    },
];
