export const team = [
    {
        name: "Civan Özseyhan",
        avatar: "/about/images/team-avatars/civan.png",
        avatar2x: "/about/images/team-avatars/civan2x.png",
        role1: "Co-Founder",
        role2: "CEO",
        url: "https://www.linkedin.com/in/civan-%C3%B6zseyhan-1ab48814/",
    },
    {
        name: "Ömer Aplak",
        avatar: "/about/images/team-avatars/omer.png",
        avatar2x: "/about/images/team-avatars/omer2x.png",
        role1: "Co-Founder",
        role2: "CTO",
        url: "https://www.linkedin.com/in/%C3%B6mer-faruk-aplak-14b87099/",
    },
    {
        name: "Eren Erkalkan",
        avatar: "/about/images/team-avatars/eren.png",
        avatar2x: "/about/images/team-avatars/eren2x.png",
        role1: "Co-Founder",
        role2: "Head of Product",
        url: "https://www.linkedin.com/in/eren-erkalkan-1b31a89a/",
    },
    {
        name: "Batuhan Özgür Özdemir",
        avatar: "/about/images/team-avatars/batuhan.png",
        avatar2x: "/about/images/team-avatars/batuhan2x.png",
        role1: "Tech Lead",
        url: "https://www.linkedin.com/in/batuhanw/",
    },
    {
        name: "Ali Emir Şen",
        avatar: "/about/images/team-avatars/ali.png",
        avatar2x: "/about/images/team-avatars/ali2x.png",
        role1: "Frontend Team Lead",
        url: "https://www.linkedin.com/in/aliemir/",
    },
    {
        name: "Yıldıray Ünlü",
        avatar: "/about/images/team-avatars/yildiray.png",
        avatar2x: "/about/images/team-avatars/yildiray2x.png",
        role1: "Backend Team Lead",
        url: "https://www.linkedin.com/in/yildirayunlu/",
    },
    {
        name: "Salih Özdemir",
        avatar: "/about/images/team-avatars/salih.png",
        avatar2x: "/about/images/team-avatars/salih2x.png",
        role1: "Software Developer",
        url: "https://www.linkedin.com/in/salihozdemr/",
    },
    {
        name: "Alican Erdurmaz",
        avatar: "/about/images/team-avatars/alican.png",
        avatar2x: "/about/images/team-avatars/alican2x.png",
        role1: "Software Developer",
        url: "https://www.linkedin.com/in/alicanerdurmaz/",
    },
    {
        name: "Necati Ozmen",
        avatar: "/about/images/team-avatars/necati.png",
        avatar2x: "/about/images/team-avatars/necati2x.png",
        role1: "Head of Content",
        url: "https://www.linkedin.com/in/necatiozmen/",
    },
    {
        name: "Recep Kütük",
        avatar: "/about/images/team-avatars/recep.png",
        avatar2x: "/about/images/team-avatars/recep2x.png",
        role1: "Senior Product Designer",
        url: "https://www.linkedin.com/in/recepkutuk/",
    },
];
