import nock from "nock";

nock("https://dev001.na-dev-engine.altogic.com:443", {
    encodedQueryParams: true,
})
    .delete("/post/613f405197d1370019b259ab")
    .reply(200, "", [
        "Date",
        "Mon, 13 Sep 2021 12:18:59 GMT",
        "Content-Type",
        "application/json; charset=utf-8",
        "Content-Length",
        "0",
        "Connection",
        "close",
        "X-Powered-By",
        "Altogic",
        "Access-Control-Allow-Origin",
        "*",
        "Surrogate-Control",
        "no-store",
        "Cache-Control",
        "no-store, no-cache, must-revalidate, proxy-revalidate",
        "Pragma",
        "no-cache",
        "Expires",
        "0",
        "Access-Control-Expose-Headers",
        "X-Service-Id, X-Duration, X-Validated-Duration, Content-Length, Content-Type, Content-Disposition, X-Powered-By",
        "X-Service-Id",
        "61373d5361cf2c001a1e27fa",
        "X-Duration",
        "11",
        "X-Validated-Duration",
        "13",
        "Strict-Transport-Security",
        "max-age=15724800; includeSubDomains",
    ]);

nock("https://dev001.na-dev-engine.altogic.com:443", {
    encodedQueryParams: true,
})
    .delete("/post/613f40854f18c4001914e7ff")
    .reply(200, "", [
        "Date",
        "Mon, 13 Sep 2021 12:18:59 GMT",
        "Content-Type",
        "application/json; charset=utf-8",
        "Content-Length",
        "0",
        "Connection",
        "close",
        "X-Powered-By",
        "Altogic",
        "Access-Control-Allow-Origin",
        "*",
        "Surrogate-Control",
        "no-store",
        "Cache-Control",
        "no-store, no-cache, must-revalidate, proxy-revalidate",
        "Pragma",
        "no-cache",
        "Expires",
        "0",
        "Access-Control-Expose-Headers",
        "X-Service-Id, X-Duration, X-Validated-Duration, Content-Length, Content-Type, Content-Disposition, X-Powered-By",
        "X-Service-Id",
        "61373d5361cf2c001a1e27fa",
        "X-Duration",
        "12",
        "X-Validated-Duration",
        "14",
        "Strict-Transport-Security",
        "max-age=15724800; includeSubDomains",
    ]);
