import nock from "nock";
import zlib from "zlib";

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post("/v1/account/sessions/anonymous", {})
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          $id: "6324787c1dbed075df81",
          $createdAt: "2022-09-16T13:22:04.128+00:00",
          userId: "6324787c1c0af1fca284",
          expire: "2023-09-16T13:22:04.121+00:00",
          provider: "anonymous",
          providerUid: "",
          providerAccessToken: "",
          providerAccessTokenExpiry: "",
          providerRefreshToken: "",
          ip: "159.146.41.20",
          osCode: "",
          osName: "",
          osVersion: "",
          clientType: "library",
          clientCode: "",
          clientName: "Node Fetch",
          clientVersion: "1.0",
          clientEngine: "",
          clientEngineVersion: "",
          deviceName: "",
          deviceBrand: "",
          deviceModel: "",
          countryCode: "tr",
          countryName: "Turkey",
          current: true,
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "299",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:22:04 GMT",
      "Server",
      "Appwrite",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5_legacy=eyJpZCI6IjYzMjQ3ODdjMWMwYWYxZmNhMjg0Iiwic2VjcmV0IjoiYTVlYjYyYTM1YTBlZDVkYWFlZWNlNWM4YmJkNzlhYWI1NmExMGQxM2YwODRhNGU4MjM5MjY4OTMzMzg1MjJmZDM3N2EzNmE0YmE0MzA1YzI0ZmU1OWM2ZDJlZTU3MDUyMmYzODU2NjQzMjRhNzQ1NjViNDY3YWQzMjBiNDFjMTZiZDVkNTFlMDZiYWNkOGQzNGVlYWEyNTM5NjBkZDBjMGJkNDQ1NzkwYjMzY2IwYTYwMjdkZTY5Zjk4MDM4YmUwYWQxNmM3MmM5ZGVlZTljYjVlNDY0NjRhZGZiMzJhNzJlOGM1ZDU2OTI3MWE5MmJhYzNkNDRiNmUyZDlhMjg3MSJ9; expires=Sat, 16-Sep-2023 13:22:04 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5=eyJpZCI6IjYzMjQ3ODdjMWMwYWYxZmNhMjg0Iiwic2VjcmV0IjoiYTVlYjYyYTM1YTBlZDVkYWFlZWNlNWM4YmJkNzlhYWI1NmExMGQxM2YwODRhNGU4MjM5MjY4OTMzMzg1MjJmZDM3N2EzNmE0YmE0MzA1YzI0ZmU1OWM2ZDJlZTU3MDUyMmYzODU2NjQzMjRhNzQ1NjViNDY3YWQzMjBiNDFjMTZiZDVkNTFlMDZiYWNkOGQzNGVlYWEyNTM5NjBkZDBjMGJkNDQ1NzkwYjMzY2IwYTYwMjdkZTY5Zjk4MDM4YmUwYWQxNmM3MmM5ZGVlZTljYjVlNDY0NjRhZGZiMzJhNzJlOGM1ZDU2OTI3MWE5MmJhYzNkNDRiNmUyZDlhMjg3MSJ9; expires=Sat, 16-Sep-2023 13:22:04 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly; samesite=None",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.022549867630005",
      "X-Fallback-Cookies",
      '{"a_session_6324555073b9706cb1f5":"eyJpZCI6IjYzMjQ3ODdjMWMwYWYxZmNhMjg0Iiwic2VjcmV0IjoiYTVlYjYyYTM1YTBlZDVkYWFlZWNlNWM4YmJkNzlhYWI1NmExMGQxM2YwODRhNGU4MjM5MjY4OTMzMzg1MjJmZDM3N2EzNmE0YmE0MzA1YzI0ZmU1OWM2ZDJlZTU3MDUyMmYzODU2NjQzMjRhNzQ1NjViNDY3YWQzMjBiNDFjMTZiZDVkNTFlMDZiYWNkOGQzNGVlYWEyNTM5NjBkZDBjMGJkNDQ1NzkwYjMzY2IwYTYwMjdkZTY5Zjk4MDM4YmUwYWQxNmM3MmM5ZGVlZTljYjVlNDY0NjRhZGZiMzJhNzJlOGM1ZDU2OTI3MWE5MmJhYzNkNDRiNmUyZDlhMjg3MSJ9"}',
      "X-Ratelimit-Limit",
      "50",
      "X-Ratelimit-Remaining",
      "45",
      "X-Ratelimit-Reset",
      "1663336800",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .get(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents/63245b3987e0f40c7988",
  )
  .reply(
    200,
    [
      zlib.gzipSync(
        JSON.stringify({
          title: "Lorem",
          description: null,
          $id: "63245b3987e0f40c7988",
          $createdAt: "2022-09-16T11:17:13.556+00:00",
          $updatedAt: "2022-09-16T11:17:13.556+00:00",
          $permissions: ['read("any")', 'update("any")', 'delete("any")'],
          $collectionId: "632455a55dc72e1aa016",
          $databaseId: "632455a0b8d017403ce9",
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "203",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:22:04 GMT",
      "Server",
      "Appwrite",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.0029749870300293",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .get(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents/632456bf1eeb69a71a78",
  )
  .reply(
    200,
    [
      zlib.gzipSync(
        JSON.stringify({
          title: "test",
          description: "test desc",
          $id: "632456bf1eeb69a71a78",
          $createdAt: "2022-09-16T10:58:07.126+00:00",
          $updatedAt: "2022-09-16T10:58:07.126+00:00",
          $permissions: [],
          $collectionId: "632455a55dc72e1aa016",
          $databaseId: "632455a0b8d017403ce9",
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "178",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:22:04 GMT",
      "Server",
      "Appwrite",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.0029268264770508",
      "Connection",
      "close",
    ],
  );
