import nock from "nock";
import zlib from "zlib";

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .post("/v1/account/sessions/anonymous", {})
  .reply(
    201,
    [
      zlib.gzipSync(
        JSON.stringify({
          $id: "632478cfd49fe8e8eb3a",
          $createdAt: "2022-09-16T13:23:27.875+00:00",
          userId: "632478cfd3c0c626b3a3",
          expire: "2023-09-16T13:23:27.870+00:00",
          provider: "anonymous",
          providerUid: "",
          providerAccessToken: "",
          providerAccessTokenExpiry: "",
          providerRefreshToken: "",
          ip: "159.146.41.20",
          osCode: "",
          osName: "",
          osVersion: "",
          clientType: "library",
          clientCode: "",
          clientName: "Node Fetch",
          clientVersion: "1.0",
          clientEngine: "",
          clientEngineVersion: "",
          deviceName: "",
          deviceBrand: "",
          deviceModel: "",
          countryCode: "tr",
          countryName: "Turkey",
          current: true,
        }),
      ),
    ],
    [
      "Access-Control-Allow-Credentials",
      "true",
      "Access-Control-Allow-Headers",
      "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
      "Access-Control-Allow-Methods",
      "GET, POST, PUT, PATCH, DELETE",
      "Access-Control-Allow-Origin",
      "https://localhost",
      "Access-Control-Expose-Headers",
      "X-Fallback-Cookies",
      "Content-Encoding",
      "gzip",
      "Content-Length",
      "299",
      "Content-Type",
      "application/json; charset=UTF-8",
      "Date",
      "Fri, 16 Sep 2022 13:23:27 GMT",
      "Server",
      "Appwrite",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5_legacy=eyJpZCI6IjYzMjQ3OGNmZDNjMGM2MjZiM2EzIiwic2VjcmV0IjoiOGYwNGY0OGQwYzljMjQ0ZDA4ZjM0YjY4YjIxNGVkN2UwZTAyMjkxMzkxN2QzMWUwOWRiZjMzNDBkN2JhYWMwODhlY2JkZWE1NzBhNDBlODdkNDBlZjc3ODRhZTYyM2EzYjM5MzE2YzllZWFjYWVmZjBmZTRiNGEzNDViNzJmNDYwZTM4ZGEzMTdlZDhiZjAwZTRiNGQ1Yjg4MWJjZmM2YWQyMjlkYjE5MDVjODI4ZjA2N2FmOTIyZmJjNjE1ZWY5NTYyMGVkNGI1YzMxYWEyOWNiYTVlNDZjYjliOGFlNDdkNDY1YTA3YjQ0N2I2ZGY0NmU5NGZmNDk2ZTM0ZTI4OSJ9; expires=Sat, 16-Sep-2023 13:23:27 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly",
      "Set-Cookie",
      "a_session_6324555073b9706cb1f5=eyJpZCI6IjYzMjQ3OGNmZDNjMGM2MjZiM2EzIiwic2VjcmV0IjoiOGYwNGY0OGQwYzljMjQ0ZDA4ZjM0YjY4YjIxNGVkN2UwZTAyMjkxMzkxN2QzMWUwOWRiZjMzNDBkN2JhYWMwODhlY2JkZWE1NzBhNDBlODdkNDBlZjc3ODRhZTYyM2EzYjM5MzE2YzllZWFjYWVmZjBmZTRiNGEzNDViNzJmNDYwZTM4ZGEzMTdlZDhiZjAwZTRiNGQ1Yjg4MWJjZmM2YWQyMjlkYjE5MDVjODI4ZjA2N2FmOTIyZmJjNjE1ZWY5NTYyMGVkNGI1YzMxYWEyOWNiYTVlNDZjYjliOGFlNDdkNDY1YTA3YjQ0N2I2ZGY0NmU5NGZmNDk2ZTM0ZTI4OSJ9; expires=Sat, 16-Sep-2023 13:23:27 GMT; path=/; domain=.matej10qa.appwrite.org; secure; httponly; samesite=None",
      "X-Content-Type-Options",
      "nosniff",
      "X-Debug-Fallback",
      "true",
      "X-Debug-Speed",
      "0.017942905426025",
      "X-Fallback-Cookies",
      '{"a_session_6324555073b9706cb1f5":"eyJpZCI6IjYzMjQ3OGNmZDNjMGM2MjZiM2EzIiwic2VjcmV0IjoiOGYwNGY0OGQwYzljMjQ0ZDA4ZjM0YjY4YjIxNGVkN2UwZTAyMjkxMzkxN2QzMWUwOWRiZjMzNDBkN2JhYWMwODhlY2JkZWE1NzBhNDBlODdkNDBlZjc3ODRhZTYyM2EzYjM5MzE2YzllZWFjYWVmZjBmZTRiNGEzNDViNzJmNDYwZTM4ZGEzMTdlZDhiZjAwZTRiNGQ1Yjg4MWJjZmM2YWQyMjlkYjE5MDVjODI4ZjA2N2FmOTIyZmJjNjE1ZWY5NTYyMGVkNGI1YzMxYWEyOWNiYTVlNDZjYjliOGFlNDdkNDY1YTA3YjQ0N2I2ZGY0NmU5NGZmNDk2ZTM0ZTI4OSJ9"}',
      "X-Ratelimit-Limit",
      "50",
      "X-Ratelimit-Remaining",
      "41",
      "X-Ratelimit-Reset",
      "1663336800",
      "Connection",
      "close",
    ],
  );

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .delete(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents/63245b2f163591192f81",
    {},
  )
  .reply(204, "", [
    "Access-Control-Allow-Credentials",
    "true",
    "Access-Control-Allow-Headers",
    "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
    "Access-Control-Allow-Methods",
    "GET, POST, PUT, PATCH, DELETE",
    "Access-Control-Allow-Origin",
    "https://localhost",
    "Access-Control-Expose-Headers",
    "X-Fallback-Cookies",
    "Content-Type",
    "text/html",
    "Date",
    "Fri, 16 Sep 2022 13:23:28 GMT",
    "Server",
    "Appwrite",
    "X-Content-Type-Options",
    "nosniff",
    "X-Debug-Fallback",
    "true",
    "X-Debug-Speed",
    "0.012737035751343",
    "X-Ratelimit-Limit",
    "60",
    "X-Ratelimit-Remaining",
    "59",
    "X-Ratelimit-Reset",
    "1663334640",
    "Connection",
    "close",
  ]);

nock("https://matej10qa.appwrite.org:443", { encodedQueryParams: true })
  .delete(
    "/v1/databases/632455a0b8d017403ce9/collections/632455a55dc72e1aa016/documents/63245b3987e0f40c7988",
    {},
  )
  .reply(204, "", [
    "Access-Control-Allow-Credentials",
    "true",
    "Access-Control-Allow-Headers",
    "Origin, Cookie, Set-Cookie, X-Requested-With, Content-Type, Access-Control-Allow-Origin, Access-Control-Request-Headers, Accept, X-Appwrite-Project, X-Appwrite-Key, X-Appwrite-Locale, X-Appwrite-Mode, X-Appwrite-JWT, X-Appwrite-Response-Format, X-SDK-Version, X-SDK-Name, X-SDK-Language, X-SDK-Platform, X-Appwrite-ID, Content-Range, Range, Cache-Control, Expires, Pragma",
    "Access-Control-Allow-Methods",
    "GET, POST, PUT, PATCH, DELETE",
    "Access-Control-Allow-Origin",
    "https://localhost",
    "Access-Control-Expose-Headers",
    "X-Fallback-Cookies",
    "Content-Type",
    "text/html",
    "Date",
    "Fri, 16 Sep 2022 13:23:28 GMT",
    "Server",
    "Appwrite",
    "X-Content-Type-Options",
    "nosniff",
    "X-Debug-Fallback",
    "true",
    "X-Debug-Speed",
    "0.013412952423096",
    "X-Ratelimit-Limit",
    "60",
    "X-Ratelimit-Remaining",
    "58",
    "X-Ratelimit-Reset",
    "1663334640",
    "Connection",
    "close",
  ]);
