import nock from "nock";

nock("https://dev001.na-dev-engine.altogic.com:443", {
    encodedQueryParams: true,
})
    .post("/post", {
        title: "foo",
        content: "bar",
        categoryId: "61373e585d65d30019e2b0a2",
        status: "rejected",
    })
    .reply(
        200,
        {
            _id: "613f405197d1370019b259ab",
            createdAt: "2021-09-13T12:13:05.371Z",
            updatedAt: "2021-09-13T12:13:05.371Z",
            title: "foo",
            categoryId: "61373e585d65d30019e2b0a2",
            status: "rejected",
            content: "bar",
        },
        [
            "Date",
            "Mon, 13 Sep 2021 12:13:05 GMT",
            "Content-Type",
            "application/json; charset=utf-8",
            "Content-Length",
            "202",
            "Connection",
            "close",
            "X-Powered-By",
            "Altogic",
            "Access-Control-Allow-Origin",
            "*",
            "Surrogate-Control",
            "no-store",
            "Cache-Control",
            "no-store, no-cache, must-revalidate, proxy-revalidate",
            "Pragma",
            "no-cache",
            "Expires",
            "0",
            "Access-Control-Expose-Headers",
            "X-Service-Id, X-Duration, X-Validated-Duration, Content-Length, Content-Type, Content-Disposition, X-Powered-By",
            "X-Service-Id",
            "61373d5361cf2c001a1e27f7",
            "X-Duration",
            "32",
            "X-Validated-Duration",
            "50",
            "Strict-Transport-Security",
            "max-age=15724800; includeSubDomains",
        ],
    );
