export const exported: string[] = [
  "Affix",
  "Anchor",
  "AutoComplete",
  "Alert",
  "Avatar",
  "BackTop",
  "Badge",
  "AntdBreadcrumb",
  "Button",
  "Calendar",
  "Card",
  "Collapse",
  "Carousel",
  "Cascader",
  "Checkbox",
  "Col",
  "ConfigProvider",
  "DatePicker",
  "Descriptions",
  "Divider",
  "Dropdown",
  "Drawer",
  "Empty",
  "FloatButton",
  "Form",
  "Grid",
  "Input",
  "Image",
  "InputNumber",
  "AntdLayout",
  "AntdList",
  "message",
  "Menu",
  "Mentions",
  "Modal",
  "Statistic",
  "notification",
  "Pagination",
  "Popconfirm",
  "Popover",
  "Progress",
  "Radio",
  "Rate",
  "Result",
  "Row",
  "Segmented",
  "Select",
  "Skeleton",
  "Slider",
  "Space",
  "Spin",
  "Steps",
  "Switch",
  "Table",
  "TimePicker",
  "Transfer",
  "Tree",
  "TreeSelect",
  "Tabs",
  "Tag",
  "Timeline",
  "Tooltip",
  "Tour",
  "Typography",
  "Upload",
  "version",
  "theme",
  "App",
  "QRCode",
  "Watermark",
  // types
  "AffixProps",
  "AnchorProps",
  "AnchorLinkProps",
  "AutoCompleteProps",
  "AlertProps",
  "AvatarProps",
  "BackTopProps",
  "BadgeProps",
  "AntdBreadcrumbProps",
  "BreadcrumbItemProps",
  "ButtonProps",
  "CalendarProps",
  "CardProps",
  "CollapseProps",
  "CollapsePanelProps",
  "CarouselProps",
  "CascaderProps",
  "CheckboxProps",
  "CheckboxOptionType",
  "ColProps",
  "DatePickerProps",
  "DescriptionsProps",
  "DividerProps",
  "DropDownProps",
  "DrawerProps",
  "EmptyProps",
  "FloatButtonProps",
  "FormInstance",
  "FormProps",
  "FormItemProps",
  "InputProps",
  "ImageProps",
  "InputNumberProps",
  "LayoutProps",
  "AntdListProps",
  "MessageArgsProps",
  "MentionProps",
  "MenuProps",
  "MenuTheme",
  "SubMenuProps",
  "MenuItemProps",
  "ModalProps",
  "ModalFuncProps",
  "StatisticProps",
  "PaginationProps",
  "PopconfirmProps",
  "PopoverProps",
  "ProgressProps",
  "RadioProps",
  "RadioChangeEvent",
  "RadioGroupProps",
  "RateProps",
  "ResultProps",
  "RowProps",
  "SelectProps",
  "SkeletonProps",
  "SliderSingleProps",
  "SpaceProps",
  "SpinProps",
  "StepProps",
  "StepsProps",
  "SwitchProps",
  "TableProps",
  "TablePaginationConfig",
  "TableColumnGroupType",
  "TableColumnType",
  "TableColumnProps",
  "TransferProps",
  "TreeSelectProps",
  "TreeProps",
  "TreeNodeProps",
  "TabsProps",
  "TabPaneProps",
  "TagProps",
  "TagType",
  "TimelineProps",
  "TimelineItemProps",
  "TooltipProps",
  "TourProps",
  "TypographyProps",
  "UploadProps",
  "WatermarkProps",
  "QRCodeProps",
  "QRPropsCanvas",
  "TitleProps",
];

export const rename: { [key: string]: string } = {
  AntdBreadcrumb: "Breadcrumb",
  AntdLayout: "Layout",
  AntdList: "List",
  AntdBreadcrumbProps: "BreadcrumbProps",
  AntdListProps: "ListProps",
};

export const renameToDefault: { [key: string]: string } = {
  Icon: "@ant-design/icons",
};

export const other: { [key: string]: string } = {
  FilterDropdownProps: "antd/lib/table/interface",
  RcFile: "antd/lib/upload/interface",
  UploadFile: "antd/lib/upload/interface",
};
