export const exported: string[] = [
  "AVAILABLE_TRANSITIONS",
  "Accordion",
  "ActionIcon",
  "Affix",
  "Alert",
  "AlphaSlider",
  "Anchor",
  "AppShell",
  "Aside",
  "AspectRatio",
  "Autocomplete",
  "Avatar",
  "BackgroundImage",
  "Badge",
  "Blockquote",
  "Box",
  "Breadcrumbs",
  "Burger",
  "Button",
  "COLOR_PICKER_SIZES",
  "Card",
  "CardSection",
  "Center",
  "CheckIcon",
  "Checkbox",
  "CheckboxIcon",
  "ChevronIcon",
  "Chip",
  "CloseButton",
  "Code",
  "Collapse",
  "Col",
  "ColorInput",
  "ColorPicker",
  // "ColorSchemeProvider",
  "ColorSwatch",
  "Container",
  "CopyButton",
  // "DEFAULT_THEME",
  "Dialog",
  "Divider",
  "Drawer",
  "FileButton",
  "FileInput",
  "FocusTrap",
  "Footer",
  "Global",
  "GlobalStyles",
  "Grid",
  "Group",
  "GroupedTransition",
  "MantineHeader",
  "Highlight",
  "HoverCard",
  "HueSlider",
  "INPUT_SIZES",
  "Image",
  "Indicator",
  "Input",
  "InputBase",
  "JsonInput",
  "Kbd",
  "MantineList",
  "Loader",
  "LoadingOverlay",
  // "MANTINE_COLORS",
  // "MANTINE_SIZES",
  "MantineProvider",
  "Mark",
  "MediaQuery",
  "Menu",
  "Modal",
  "MultiSelect",
  "NativeSelect",
  "NavLink",
  "Navbar",
  // "NormalizeCSS",
  "Notification",
  "NumberInput",
  "OptionalPortal",
  "Overlay",
  "Pagination",
  "Paper",
  "PasswordInput",
  "Popover",
  "Portal",
  "Progress",
  "Radio",
  "RangeSlider",
  "RingProgress",
  "ScrollArea",
  "SegmentedControl",
  "Select",
  "SelectChevronIcon",
  "SimpleGrid",
  "Skeleton",
  "Slider",
  "Space",
  "Spoiler",
  "Stack",
  "Step",
  "Stepper",
  "Switch",
  "Table",
  "Tabs",
  "Text",
  "TextInput",
  "Textarea",
  "ThemeIcon",
  "Timeline",
  "TimelineItem",
  "Title",
  "Tooltip",
  "TransferList",
  "Transition",
  "TypographyStylesProvider",
  "UnstyledButton",
  // "clsx",
  // "createEmotionCache",
  "createPolymorphicComponent",
  // "createStyles",
  // "defaultMantineEmotionCache",
  "extractSystemStyles",
  // "getDefaultZIndex",
  "getSortedBreakpoints",
  // "keyframes",
  "packSx",
  // "useComponentDefaultProps",
  // "useCss",
  // "useEmotionCache",
  "useInputProps",
  "useMantineColorScheme",
  // "useMantineTheme",
  "validateJson",
  // types
  "AccordionControlProps",
  "AccordionItemProps",
  "AccordionPanelProps",
  "AccordionProps",
  "AccordionStylesNames",
  "AccordionStylesParams",
  "ActionIconProps",
  "ActionIconStylesNames",
  "ActionIconStylesParams",
  "ActionIconVariant",
  "AffixProps",
  "AlertProps",
  "AlertStylesNames",
  "AlertStylesParams",
  "AlphaSliderProps",
  "AnchorProps",
  "AppShellProps",
  "AppShellStylesNames",
  "AppShellStylesParams",
  "AsideProps",
  "AspectRatioProps",
  "AspectRatioStylesParams",
  "AutocompleteItem",
  "AutocompleteProps",
  "AutocompleteStylesNames",
  "AvatarProps",
  "AvatarStylesNames",
  "AvatarStylesParams",
  "BackgroundImageProps",
  "BadgeProps",
  "BadgeStylesNames",
  "BadgeStylesParams",
  "BadgeVariant",
  "BaseSelectProps",
  "BlockquoteProps",
  "BlockquoteStylesNames",
  "BlockquoteStylesParams",
  "BoxProps",
  "BreadcrumbsProps",
  "BreadcrumbsStylesNames",
  "BurgerProps",
  "BurgerStylesNames",
  "BurgerStylesParams",
  "ButtonGroupProps",
  "ButtonGroupStylesParams",
  "ButtonProps",
  "ButtonStylesNames",
  "ButtonStylesParams",
  "ButtonVariant",
  "CSSObject",
  "CardProps",
  "CardSectionProps",
  "CenterProps",
  "CheckboxGroupProps",
  "CheckboxGroupStylesNames",
  "CheckboxIconProps",
  "CheckboxProps",
  "CheckboxStylesNames",
  "CheckboxStylesParams",
  "ChipGroupProps",
  "ChipProps",
  "ChipStylesNames",
  "ChipStylesParams",
  "ClassNames",
  "CloseButtonProps",
  "CodeProps",
  "CodeStylesParams",
  "ColProps",
  "CollapseProps",
  "ColorInputProps",
  "ColorInputStylesNames",
  "ColorPickerBaseProps",
  "ColorPickerProps",
  "ColorPickerStylesNames",
  "ColorPickerStylesParams",
  "ColorScheme",
  "ColorSwatchProps",
  "ColorSwatchStylesNames",
  "ColorSwatchStylesParams",
  "ContainerProps",
  "ContainerStylesParams",
  "CopyButtonProps",
  "DefaultMantineColor",
  "DefaultProps",
  "DialogProps",
  "DialogStylesNames",
  "DialogStylesParams",
  "DividerProps",
  "DividerStylesNames",
  "DividerStylesParams",
  "DrawerPosition",
  "DrawerProps",
  "DrawerStylesNames",
  "DrawerStylesParams",
  "EmotionCache",
  "FileButtonProps",
  "FileInputProps",
  "FileInputStylesNames",
  "FocusTrapProps",
  "FooterProps",
  "GridProps",
  "GroupProps",
  "GroupedTransitionProps",
  "HighlightProps",
  "MatineHeaderProps",
  "HoverCardDropdownProps",
  "HoverCardTargetProps",
  "HoverCardProps",
  "HueSliderProps",
  "ImageProps",
  "ImageStylesNames",
  "ImageStylesParams",
  "IndicatorProps",
  "IndicatorStylesNames",
  "IndicatorStylesParams",
  "InputBaseProps",
  "InputBaseStylesNames",
  "InputDescriptionProps",
  "InputDescriptionStylesNames",
  "InputErrorProps",
  "InputErrorStylesNames",
  "InputLabelProps",
  "InputLabelStylesNames",
  "InputProps",
  "InputSharedProps",
  "InputStylesNames",
  "InputStylesParams",
  "InputVariant",
  "InputWrapperBaseProps",
  "InputWrapperProps",
  "InputWrapperStylesNames",
  "JsonInputProps",
  "JsonInputStylesNames",
  "JsonInputStylesParams",
  "KbdProps",
  "ListItemProps",
  "MantineListProps",
  "ListStylesNames",
  "ListItemStylesNames",
  "ListStylesParams",
  "LoaderProps",
  "LoadingOverlayProps",
  "MantineColor",
  "MantineGradient",
  "MantineNumberSize",
  "MantineProviderProps",
  "MantineShadow",
  "MantineSize",
  "MantineSizes",
  "MantineStyleSystemProps",
  "MantineStyleSystemSize",
  "MantineTheme",
  "MantineThemeBase",
  "MantineThemeColors",
  "MantineThemeColorsOverride",
  "MantineThemeOther",
  "MantineThemeOverride",
  "MantineTransition",
  "MarkProps",
  "MarkStylesParams",
  "MediaQueryProps",
  "MediaQueryStylesParams",
  "MenuDividerProps",
  "MenuDropdownProps",
  "MenuItemProps",
  "MenuLabelProps",
  "MenuProps",
  "MenuStylesNames",
  "MenuTargetProps",
  "ModalProps",
  "ModalStylesNames",
  "ModalStylesParams",
  "MultiSelectProps",
  "MultiSelectStylesNames",
  "MultiSelectStylesParams",
  "MultiSelectValueProps",
  "NativeSelectProps",
  "NativeSelectStylesNames",
  "NavLinkProps",
  "NavLinkStylesNames",
  "NavLinkStylesParams",
  "NavbarProps",
  "NotificationProps",
  "NotificationStylesNames",
  "NotificationStylesParams",
  "NumberInputHandlers",
  "NumberInputProps",
  "NumberInputStylesNames",
  "NumberInputStylesParams",
  "OptionalPortalProps",
  "OverlayProps",
  "PaginationItemProps",
  "PaginationProps",
  "PaginationStylesNames",
  "PaginationStylesParams",
  "PaperProps",
  "PaperStylesParams",
  "PasswordInputProps",
  "PasswordInputStylesNames",
  "PasswordInputStylesParams",
  "PopoverBaseProps",
  "PopoverDropdownProps",
  "PopoverProps",
  "PopoverStylesNames",
  "PopoverStylesParams",
  "PopoverTargetProps",
  "PortalProps",
  "ProgressProps",
  "ProgressStylesNames",
  "ProgressStylesParams",
  "RadioGroupProps",
  "RadioGroupStylesNames",
  "RadioProps",
  "RadioStylesNames",
  "RadioStylesParams",
  "RangeSliderProps",
  "RingProgressProps",
  "RingProgressStylesNames",
  "ScrollAreaProps",
  "ScrollAreaStylesNames",
  "ScrollAreaStylesParams",
  "SegmentedControlItem",
  "SegmentedControlProps",
  "SegmentedControlStylesNames",
  "SegmentedControlStylesParams",
  "SelectItem",
  "SelectItemProps",
  "SelectProps",
  "SelectStylesNames",
  "Selectors",
  "SimpleGridBreakpoint",
  "SimpleGridProps",
  "SimpleGridStylesParams",
  "SkeletonProps",
  "SkeletonStylesParams",
  "SliderProps",
  "SliderStylesNames",
  "SpaceProps",
  "SpoilerProps",
  "SpoilerStylesNames",
  "SpoilerStylesParams",
  "StackProps",
  "StackStylesParams",
  "StepProps",
  "StepStylesParams",
  "StepperProps",
  "StepperStylesNames",
  "StepperStylesParams",
  "Styles",
  "SwitchProps",
  "SwitchStylesNames",
  "SwitchStylesParams",
  "Sx",
  "TabProps",
  "TableProps",
  "TableStylesParams",
  "TabsListProps",
  "TabsOrientation",
  "TabsPanelProps",
  "TabsProps",
  "TabsStylesNames",
  "TabsStylesParams",
  "TabsValue",
  "TabsVariant",
  "TextInputProps",
  "TextInputStylesNames",
  "TextProps",
  "TextStylesParams",
  "TextareaProps",
  "ThemeIconProps",
  "ThemeIconStylesParams",
  "ThemeIconVariant",
  "TimelineItemProps",
  "TimelineItemStylesNames",
  "TimelineProps",
  "TitleOrder",
  "TitleProps",
  "TitleStylesParams",
  "TooltipFloatingProps",
  "TooltipGroupProps",
  "TooltipProps",
  "TooltipStylesNames",
  "TooltipStylesParams",
  "TransferListData",
  "TransferListItem",
  "TransferListItemComponent",
  "TransferListItemComponentProps",
  "TransferListProps",
  "TransferListStylesNames",
  "TransitionProps",
  "Tuple",
  "TypographyStylesProviderProps",
  "UnstyledButtonProps",
  "UseStylesOptions",
];

export const rename: { [key: string]: string } = {
  MantineHeader: "Header",
  MantineList: "List",
  MatineHeaderProps: "HeaderProps",
  MantineListProps: "ListProps",
};

export const other: { [key: string]: string } = {
  NotificationsProvider: "@mantine/notifications",
  cleanNotifications: "@mantine/notifications",
  cleanNotificationsQueue: "@mantine/notifications",
  hideNotification: "@mantine/notifications",
  showNotification: "@mantine/notifications",
  updateNotification: "@mantine/notifications",
  useNotifications: "@mantine/notifications",
  //
  assignRef: "@mantine/hooks",
  clamp: "@mantine/hooks",
  clampUseMovePosition: "@mantine/hooks",
  getHotkeyHandler: "@mantine/hooks",
  lowerFirst: "@mantine/hooks",
  mergeRefs: "@mantine/hooks",
  randomId: "@mantine/hooks",
  range: "@mantine/hooks",
  shallowEqual: "@mantine/hooks",
  upperFirst: "@mantine/hooks",
  useClickOutside: "@mantine/hooks",
  useClipboard: "@mantine/hooks",
  useColorScheme: "@mantine/hooks",
  useCounter: "@mantine/hooks",
  useDebouncedState: "@mantine/hooks",
  useDebouncedValue: "@mantine/hooks",
  useDidUpdate: "@mantine/hooks",
  useDisclosure: "@mantine/hooks",
  useDocumentTitle: "@mantine/hooks",
  useDocumentVisibility: "@mantine/hooks",
  useElementSize: "@mantine/hooks",
  useEventListener: "@mantine/hooks",
  useEyeDropper: "@mantine/hooks",
  useFavicon: "@mantine/hooks",
  useFocusReturn: "@mantine/hooks",
  useFocusTrap: "@mantine/hooks",
  useFocusWithin: "@mantine/hooks",
  useForceUpdate: "@mantine/hooks",
  useFullscreen: "@mantine/hooks",
  useHash: "@mantine/hooks",
  useHotkeys: "@mantine/hooks",
  useHover: "@mantine/hooks",
  useId: "@mantine/hooks",
  useIdle: "@mantine/hooks",
  useInputState: "@mantine/hooks",
  useIntersection: "@mantine/hooks",
  useInterval: "@mantine/hooks",
  useIsomorphicEffect: "@mantine/hooks",
  useListState: "@mantine/hooks",
  useLocalStorage: "@mantine/hooks",
  useLogger: "@mantine/hooks",
  useMediaQuery: "@mantine/hooks",
  useMergedRef: "@mantine/hooks",
  useMouse: "@mantine/hooks",
  useMove: "@mantine/hooks",
  useNetwork: "@mantine/hooks",
  useOs: "@mantine/hooks",
  usePageLeave: "@mantine/hooks",
  usePagination: "@mantine/hooks",
  usePrevious: "@mantine/hooks",
  useQueue: "@mantine/hooks",
  useReducedMotion: "@mantine/hooks",
  useResizeObserver: "@mantine/hooks",
  useScrollIntoView: "@mantine/hooks",
  useScrollLock: "@mantine/hooks",
  useSessionStorage: "@mantine/hooks",
  useSetState: "@mantine/hooks",
  useShallowEffect: "@mantine/hooks",
  useTextSelection: "@mantine/hooks",
  useTimeout: "@mantine/hooks",
  useToggle: "@mantine/hooks",
  useUncontrolled: "@mantine/hooks",
  useValidatedState: "@mantine/hooks",
  useViewportSize: "@mantine/hooks",
  useWindowEvent: "@mantine/hooks",
  useWindowScroll: "@mantine/hooks",
  //
  ColorSchemeProvider: "@mantine/styles",
  DEFAULT_THEME: "@mantine/styles",
  // Global: "@mantine/styles",
  // GlobalStyles: "@mantine/styles",
  MANTINE_COLORS: "@mantine/styles",
  MANTINE_SIZES: "@mantine/styles",
  // MantineProvider: "@mantine/styles",
  NormalizeCSS: "@mantine/styles",
  clsx: "@mantine/styles",
  createEmotionCache: "@mantine/styles",
  createStyles: "@mantine/styles",
  defaultMantineEmotionCache: "@mantine/styles",
  filterProps: "@mantine/styles",
  getDefaultZIndex: "@mantine/styles",
  keyframes: "@mantine/styles",
  useComponentDefaultProps: "@mantine/styles",
  useCss: "@mantine/styles",
  useEmotionCache: "@mantine/styles",
  // useMantineColorScheme: "@mantine/styles",
  useMantineTheme: "@mantine/styles",
};
